// Generated by `cargo run --bin regen_fixtures` — do not edit manually.
pub const EXPR_DIGEST: [u8; 32] = [
    0x7c, 0x70, 0x31, 0x08, 0x15, 0x5a, 0x8c, 0x7d,
    0xba, 0x21, 0xbd, 0xa0, 0xa2, 0x03, 0x28, 0xb4,
    0x49, 0x91, 0x81, 0x38, 0x43, 0x0c, 0xb3, 0xff,
    0xc6, 0xfe, 0x7b, 0xcb, 0x12, 0xed, 0x39, 0x3d,
];
pub fn add32_demo(a: u32, b: u32) -> u32 {
    const POOL: &[u32] = &[
        0xcd2c6f7f,
        0xbb2a3fb2,
        0x070f4649,
        0xcd2c6f7f,
        0xbb2a3fb2,
        0x00000001,
        0x00000001,
        0x00000002,
        0x00000002,
        0xc6017c94,
        0x00000000,
        0x00000002,
        0x00000004,
        0x00000004,
        0xcf310a12,
        0x00000004,
        0x8c02f92d,
        0x00000008,
        0x00000008,
        0x069dc10a,
        0x00000008,
        0x9e62142d,
        0x00000010,
        0x00000010,
        0xabe5f6d0,
        0x00000000,
        0x0d3b8214,
        0x00000020,
        0x00000020,
        0x958b761d,
        0x00000000,
        0x57cbed81,
        0x00000040,
        0x00000040,
        0xdee17b51,
        0x00000040,
        0x2b16ec7b,
        0x00000080,
        0x00000080,
        0x431d9dd4,
        0x00000080,
        0xbdc2f6a3,
        0x00000100,
        0x00000100,
        0x1f71c422,
        0x00000000,
        0x863b3aa8,
        0x00000200,
        0x00000200,
        0xc5a0ef11,
        0x00000000,
        0x3ee38a44,
        0x00000400,
        0x00000400,
        0x12037913,
        0x00000000,
        0x8b41de23,
        0x00000800,
        0x00000800,
        0x37fc854f,
        0x00000000,
        0x2406f226,
        0x00001000,
        0x00001000,
        0xc9ff71c7,
        0x00001000,
        0x6ff91a9e,
        0x00002000,
        0x00002000,
        0xcb30ce1a,
        0x00000000,
        0x93fec38f,
        0x00004000,
        0x00004000,
        0x9e0d3fac,
        0x00004000,
        0x9661dc35,
        0x00008000,
        0x00008000,
        0xbfd4a4ae,
        0x00000000,
        0x3c1a7f59,
        0x00010000,
        0x00010000,
        0x87b83854,
        0x00000000,
        0x7fa9495d,
        0x00020000,
        0x00020000,
        0xf80e4de3,
        0x00020000,
        0x0f7270a9,
        0x00040000,
        0x00040000,
        0xd99c7f7e,
        0x00040000,
        0xf01c9bc7,
        0x00080000,
        0x00080000,
        0xff0ea77d,
        0x00000000,
        0xb338fefd,
        0x00100000,
        0x00100000,
        0x48501800,
        0x00000000,
        0xfe1d4efb,
        0x00200000,
        0x00200000,
        0x23ae2c7b,
        0x00000000,
        0x90a03000,
        0x00400000,
        0x00400000,
        0x0bd4b7bb,
        0x00000000,
        0x471c58f6,
        0x00800000,
        0x00800000,
        0x1ce4b87b,
        0x00000000,
        0x17a96f76,
        0x01000000,
        0x01000000,
        0xfd960655,
        0x00000000,
        0x39c970f6,
        0x02000000,
        0x02000000,
        0xf4ff78ef,
        0x02000000,
        0xfb2c0cab,
        0x04000000,
        0x04000000,
        0x34bb13f0,
        0x04000000,
        0xe9fef1df,
        0x08000000,
        0x08000000,
        0x0ca57b62,
        0x00000000,
        0x617627e0,
        0x10000000,
        0x10000000,
        0x6e3bd6a2,
        0x10000000,
        0x094af6c4,
        0x20000000,
        0x20000000,
        0x6cfacf84,
        0x20000000,
        0xdc77ad44,
        0x40000000,
        0x40000000,
        0xe6e1329a,
        0x40000000,
        0xd9f59f08,
        0x80000000,
        0xef31307c,
    ];
    let mut r = [0u32; 7];
    r[3] = a ^ POOL[0];
    r[0] = b ^ POOL[1];
    r[5] = {
        let (t, ma, mb) = (POOL[2], POOL[3], POOL[4]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[6] = r[3] ^ r[0];
    r[3] = r[6] & POOL[5];
    r[0] = r[5] & POOL[6];
    r[2] = r[0].rotate_left(1);
    r[0] = r[6] & POOL[7];
    r[1] = r[0] ^ r[2];
    r[4] = r[3] ^ r[1];
    r[3] = r[5] & POOL[8];
    r[1] = {
        let (t, ma, mb) = (POOL[9], POOL[10], POOL[11]);
        let mut z = t;
        z ^= r[0] & mb;
        z ^= r[2] & ma;
        z ^= r[0] & r[2];
        z
    };
    r[0] = r[3] ^ r[1];
    r[3] = r[0].rotate_left(1);
    r[0] = r[6] & POOL[12];
    r[2] = r[0] ^ r[3];
    r[1] = r[4] ^ r[2];
    r[2] = r[5] & POOL[13];
    r[4] = {
        let (t, ma, mb) = (POOL[14], POOL[15], POOL[16]);
        let mut z = t;
        z ^= r[0] & mb;
        z ^= r[3] & ma;
        z ^= r[0] & r[3];
        z
    };
    r[3] = r[2] ^ r[4];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[17];
    r[2] = r[3] ^ r[0];
    r[4] = r[1] ^ r[2];
    r[2] = r[5] & POOL[18];
    r[1] = {
        let (t, ma, mb) = (POOL[19], POOL[20], POOL[21]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[1];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[22];
    r[2] = r[3] ^ r[0];
    r[1] = r[4] ^ r[2];
    r[2] = r[5] & POOL[23];
    r[4] = {
        let (t, ma, mb) = (POOL[24], POOL[25], POOL[26]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[4];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[27];
    r[2] = r[3] ^ r[0];
    r[4] = r[1] ^ r[2];
    r[2] = r[5] & POOL[28];
    r[1] = {
        let (t, ma, mb) = (POOL[29], POOL[30], POOL[31]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[1];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[32];
    r[2] = r[3] ^ r[0];
    r[1] = r[4] ^ r[2];
    r[2] = r[5] & POOL[33];
    r[4] = {
        let (t, ma, mb) = (POOL[34], POOL[35], POOL[36]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[4];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[37];
    r[2] = r[3] ^ r[0];
    r[4] = r[1] ^ r[2];
    r[2] = r[5] & POOL[38];
    r[1] = {
        let (t, ma, mb) = (POOL[39], POOL[40], POOL[41]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[1];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[42];
    r[2] = r[3] ^ r[0];
    r[1] = r[4] ^ r[2];
    r[2] = r[5] & POOL[43];
    r[4] = {
        let (t, ma, mb) = (POOL[44], POOL[45], POOL[46]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[4];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[47];
    r[2] = r[3] ^ r[0];
    r[4] = r[1] ^ r[2];
    r[2] = r[5] & POOL[48];
    r[1] = {
        let (t, ma, mb) = (POOL[49], POOL[50], POOL[51]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[1];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[52];
    r[2] = r[3] ^ r[0];
    r[1] = r[4] ^ r[2];
    r[2] = r[5] & POOL[53];
    r[4] = {
        let (t, ma, mb) = (POOL[54], POOL[55], POOL[56]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[4];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[57];
    r[2] = r[3] ^ r[0];
    r[4] = r[1] ^ r[2];
    r[2] = r[5] & POOL[58];
    r[1] = {
        let (t, ma, mb) = (POOL[59], POOL[60], POOL[61]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[1];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[62];
    r[2] = r[3] ^ r[0];
    r[1] = r[4] ^ r[2];
    r[2] = r[5] & POOL[63];
    r[4] = {
        let (t, ma, mb) = (POOL[64], POOL[65], POOL[66]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[4];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[67];
    r[2] = r[3] ^ r[0];
    r[4] = r[1] ^ r[2];
    r[2] = r[5] & POOL[68];
    r[1] = {
        let (t, ma, mb) = (POOL[69], POOL[70], POOL[71]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[1];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[72];
    r[2] = r[3] ^ r[0];
    r[1] = r[4] ^ r[2];
    r[2] = r[5] & POOL[73];
    r[4] = {
        let (t, ma, mb) = (POOL[74], POOL[75], POOL[76]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[4];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[77];
    r[2] = r[3] ^ r[0];
    r[4] = r[1] ^ r[2];
    r[2] = r[5] & POOL[78];
    r[1] = {
        let (t, ma, mb) = (POOL[79], POOL[80], POOL[81]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[1];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[82];
    r[2] = r[3] ^ r[0];
    r[1] = r[4] ^ r[2];
    r[2] = r[5] & POOL[83];
    r[4] = {
        let (t, ma, mb) = (POOL[84], POOL[85], POOL[86]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[4];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[87];
    r[2] = r[3] ^ r[0];
    r[4] = r[1] ^ r[2];
    r[2] = r[5] & POOL[88];
    r[1] = {
        let (t, ma, mb) = (POOL[89], POOL[90], POOL[91]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[1];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[92];
    r[2] = r[3] ^ r[0];
    r[1] = r[4] ^ r[2];
    r[2] = r[5] & POOL[93];
    r[4] = {
        let (t, ma, mb) = (POOL[94], POOL[95], POOL[96]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[4];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[97];
    r[2] = r[3] ^ r[0];
    r[4] = r[1] ^ r[2];
    r[2] = r[5] & POOL[98];
    r[1] = {
        let (t, ma, mb) = (POOL[99], POOL[100], POOL[101]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[1];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[102];
    r[2] = r[3] ^ r[0];
    r[1] = r[4] ^ r[2];
    r[2] = r[5] & POOL[103];
    r[4] = {
        let (t, ma, mb) = (POOL[104], POOL[105], POOL[106]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[4];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[107];
    r[2] = r[3] ^ r[0];
    r[4] = r[1] ^ r[2];
    r[2] = r[5] & POOL[108];
    r[1] = {
        let (t, ma, mb) = (POOL[109], POOL[110], POOL[111]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[1];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[112];
    r[2] = r[3] ^ r[0];
    r[1] = r[4] ^ r[2];
    r[2] = r[5] & POOL[113];
    r[4] = {
        let (t, ma, mb) = (POOL[114], POOL[115], POOL[116]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[4];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[117];
    r[2] = r[3] ^ r[0];
    r[4] = r[1] ^ r[2];
    r[2] = r[5] & POOL[118];
    r[1] = {
        let (t, ma, mb) = (POOL[119], POOL[120], POOL[121]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[1];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[122];
    r[2] = r[3] ^ r[0];
    r[1] = r[4] ^ r[2];
    r[2] = r[5] & POOL[123];
    r[4] = {
        let (t, ma, mb) = (POOL[124], POOL[125], POOL[126]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[4];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[127];
    r[2] = r[3] ^ r[0];
    r[4] = r[1] ^ r[2];
    r[2] = r[5] & POOL[128];
    r[1] = {
        let (t, ma, mb) = (POOL[129], POOL[130], POOL[131]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[1];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[132];
    r[2] = r[3] ^ r[0];
    r[1] = r[4] ^ r[2];
    r[2] = r[5] & POOL[133];
    r[4] = {
        let (t, ma, mb) = (POOL[134], POOL[135], POOL[136]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[4];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[137];
    r[2] = r[3] ^ r[0];
    r[4] = r[1] ^ r[2];
    r[2] = r[5] & POOL[138];
    r[1] = {
        let (t, ma, mb) = (POOL[139], POOL[140], POOL[141]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[1];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[142];
    r[2] = r[3] ^ r[0];
    r[1] = r[4] ^ r[2];
    r[2] = r[5] & POOL[143];
    r[4] = {
        let (t, ma, mb) = (POOL[144], POOL[145], POOL[146]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[4];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[147];
    r[2] = r[3] ^ r[0];
    r[4] = r[1] ^ r[2];
    r[2] = r[5] & POOL[148];
    r[1] = {
        let (t, ma, mb) = (POOL[149], POOL[150], POOL[151]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[1];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[152];
    r[2] = r[3] ^ r[0];
    r[1] = r[4] ^ r[2];
    r[2] = r[5] & POOL[153];
    r[5] = {
        let (t, ma, mb) = (POOL[154], POOL[155], POOL[156]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[2] ^ r[5];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[157];
    r[5] = r[3] ^ r[0];
    r[3] = r[1] ^ r[5];
    r[3] ^ POOL[158]
}
