// Generated by `cargo run --bin regen_fixtures` — do not edit manually.
pub fn add32_demo(a: u32, b: u32) -> u32 {
    const POOL: &[u32] = &[
        0x8e27697b,
        0xc6017c94,
        0x49306206,
        0x8e27697b,
        0xc6017c94,
        0x00000001,
        0x00000001,
        0x00000002,
        0x00000002,
        0x069dc102,
        0x00000002,
        0x00000000,
        0x00000004,
        0x00000004,
        0xabe5f6d0,
        0x00000004,
        0x0d3b8200,
        0x00000008,
        0x00000008,
        0x958b7615,
        0x00000008,
        0x57cbeda9,
        0x00000010,
        0x00000010,
        0xdee17b11,
        0x00000000,
        0x2b16ec3b,
        0x00000020,
        0x00000020,
        0x431d9d54,
        0x00000020,
        0xbdc2f603,
        0x00000040,
        0x00000040,
        0x1f71c422,
        0x00000040,
        0x863b3aa8,
        0x00000080,
        0x00000080,
        0xc5a0ef11,
        0x00000080,
        0x3ee38844,
        0x00000100,
        0x00000100,
        0x12037913,
        0x00000100,
        0x8b41de23,
        0x00000200,
        0x00000200,
        0x37fc854f,
        0x00000000,
        0x2406f226,
        0x00000400,
        0x00000400,
        0xc9ff65c7,
        0x00000400,
        0x6ff90e9e,
        0x00000800,
        0x00000800,
        0xcb30ce1a,
        0x00000000,
        0x93fec38f,
        0x00001000,
        0x00001000,
        0x9e0d7fac,
        0x00001000,
        0x96618c35,
        0x00002000,
        0x00002000,
        0xbfd4a4ae,
        0x00000000,
        0x3c1aff59,
        0x00004000,
        0x00004000,
        0x87b83854,
        0x00000000,
        0x7fa9495d,
        0x00008000,
        0x00008000,
        0xf80c4de3,
        0x00000000,
        0x0f7070a9,
        0x00010000,
        0x00010000,
        0xd9987f7e,
        0x00000000,
        0xf0189bc7,
        0x00020000,
        0x00020000,
        0xff0ca77d,
        0x00020000,
        0xb332fefd,
        0x00040000,
        0x00040000,
        0x48541800,
        0x00040000,
        0xfe1d4efb,
        0x00080000,
        0x00080000,
        0x23ae2c7b,
        0x00000000,
        0x90a03000,
        0x00100000,
        0x00100000,
        0x0bd4b7bb,
        0x00000000,
        0x475c58f6,
        0x00200000,
        0x00200000,
        0x1ce4b87b,
        0x00200000,
        0x17896f76,
        0x00400000,
        0x00400000,
        0xfd960655,
        0x00000000,
        0x398970f6,
        0x00800000,
        0x00800000,
        0xf6ff78ef,
        0x00000000,
        0xfb2c0cab,
        0x01000000,
        0x01000000,
        0x34bb13f0,
        0x00000000,
        0xedfef1df,
        0x02000000,
        0x02000000,
        0x0ca57b62,
        0x00000000,
        0x6b7627e0,
        0x04000000,
        0x04000000,
        0x6e3bd6a2,
        0x00000000,
        0x1d4af6c4,
        0x08000000,
        0x08000000,
        0x6cfacf84,
        0x08000000,
        0xd477ad44,
        0x10000000,
        0x10000000,
        0xa6e1329a,
        0x00000000,
        0xc9f59f08,
        0x20000000,
        0x20000000,
        0x75e88c63,
        0x00000000,
        0x4dc26535,
        0x40000000,
        0x40000000,
        0x70f0a328,
        0x40000000,
        0xebd118c6,
        0x80000000,
        0xcb6d0016,
    ];
    let mut r = [0u32; 7];
    r[5] = a ^ POOL[0];
    r[3] = b ^ POOL[1];
    r[1] = {
        let (t, ma, mb) = (POOL[2], POOL[3], POOL[4]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[6] = r[5] ^ r[3];
    r[5] = r[6] & POOL[5];
    r[3] = r[1] & POOL[6];
    r[0] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[7];
    r[4] = r[3] ^ r[0];
    r[2] = r[5] ^ r[4];
    r[5] = r[1] & POOL[8];
    r[4] = {
        let (t, ma, mb) = (POOL[9], POOL[10], POOL[11]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[5] ^ r[4];
    r[5] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[12];
    r[0] = r[3] ^ r[5];
    r[4] = r[2] ^ r[0];
    r[0] = r[1] & POOL[13];
    r[2] = {
        let (t, ma, mb) = (POOL[14], POOL[15], POOL[16]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[5] & ma;
        z ^= r[3] & r[5];
        z
    };
    r[5] = r[0] ^ r[2];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[17];
    r[0] = r[5] ^ r[3];
    r[2] = r[4] ^ r[0];
    r[0] = r[1] & POOL[18];
    r[4] = {
        let (t, ma, mb) = (POOL[19], POOL[20], POOL[21]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[4];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[22];
    r[0] = r[5] ^ r[3];
    r[4] = r[2] ^ r[0];
    r[0] = r[1] & POOL[23];
    r[2] = {
        let (t, ma, mb) = (POOL[24], POOL[25], POOL[26]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[2];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[27];
    r[0] = r[5] ^ r[3];
    r[2] = r[4] ^ r[0];
    r[0] = r[1] & POOL[28];
    r[4] = {
        let (t, ma, mb) = (POOL[29], POOL[30], POOL[31]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[4];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[32];
    r[0] = r[5] ^ r[3];
    r[4] = r[2] ^ r[0];
    r[0] = r[1] & POOL[33];
    r[2] = {
        let (t, ma, mb) = (POOL[34], POOL[35], POOL[36]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[2];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[37];
    r[0] = r[5] ^ r[3];
    r[2] = r[4] ^ r[0];
    r[0] = r[1] & POOL[38];
    r[4] = {
        let (t, ma, mb) = (POOL[39], POOL[40], POOL[41]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[4];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[42];
    r[0] = r[5] ^ r[3];
    r[4] = r[2] ^ r[0];
    r[0] = r[1] & POOL[43];
    r[2] = {
        let (t, ma, mb) = (POOL[44], POOL[45], POOL[46]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[2];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[47];
    r[0] = r[5] ^ r[3];
    r[2] = r[4] ^ r[0];
    r[0] = r[1] & POOL[48];
    r[4] = {
        let (t, ma, mb) = (POOL[49], POOL[50], POOL[51]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[4];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[52];
    r[0] = r[5] ^ r[3];
    r[4] = r[2] ^ r[0];
    r[0] = r[1] & POOL[53];
    r[2] = {
        let (t, ma, mb) = (POOL[54], POOL[55], POOL[56]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[2];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[57];
    r[0] = r[5] ^ r[3];
    r[2] = r[4] ^ r[0];
    r[0] = r[1] & POOL[58];
    r[4] = {
        let (t, ma, mb) = (POOL[59], POOL[60], POOL[61]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[4];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[62];
    r[0] = r[5] ^ r[3];
    r[4] = r[2] ^ r[0];
    r[0] = r[1] & POOL[63];
    r[2] = {
        let (t, ma, mb) = (POOL[64], POOL[65], POOL[66]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[2];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[67];
    r[0] = r[5] ^ r[3];
    r[2] = r[4] ^ r[0];
    r[0] = r[1] & POOL[68];
    r[4] = {
        let (t, ma, mb) = (POOL[69], POOL[70], POOL[71]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[4];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[72];
    r[0] = r[5] ^ r[3];
    r[4] = r[2] ^ r[0];
    r[0] = r[1] & POOL[73];
    r[2] = {
        let (t, ma, mb) = (POOL[74], POOL[75], POOL[76]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[2];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[77];
    r[0] = r[5] ^ r[3];
    r[2] = r[4] ^ r[0];
    r[0] = r[1] & POOL[78];
    r[4] = {
        let (t, ma, mb) = (POOL[79], POOL[80], POOL[81]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[4];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[82];
    r[0] = r[5] ^ r[3];
    r[4] = r[2] ^ r[0];
    r[0] = r[1] & POOL[83];
    r[2] = {
        let (t, ma, mb) = (POOL[84], POOL[85], POOL[86]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[2];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[87];
    r[0] = r[5] ^ r[3];
    r[2] = r[4] ^ r[0];
    r[0] = r[1] & POOL[88];
    r[4] = {
        let (t, ma, mb) = (POOL[89], POOL[90], POOL[91]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[4];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[92];
    r[0] = r[5] ^ r[3];
    r[4] = r[2] ^ r[0];
    r[0] = r[1] & POOL[93];
    r[2] = {
        let (t, ma, mb) = (POOL[94], POOL[95], POOL[96]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[2];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[97];
    r[0] = r[5] ^ r[3];
    r[2] = r[4] ^ r[0];
    r[0] = r[1] & POOL[98];
    r[4] = {
        let (t, ma, mb) = (POOL[99], POOL[100], POOL[101]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[4];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[102];
    r[0] = r[5] ^ r[3];
    r[4] = r[2] ^ r[0];
    r[0] = r[1] & POOL[103];
    r[2] = {
        let (t, ma, mb) = (POOL[104], POOL[105], POOL[106]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[2];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[107];
    r[0] = r[5] ^ r[3];
    r[2] = r[4] ^ r[0];
    r[0] = r[1] & POOL[108];
    r[4] = {
        let (t, ma, mb) = (POOL[109], POOL[110], POOL[111]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[4];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[112];
    r[0] = r[5] ^ r[3];
    r[4] = r[2] ^ r[0];
    r[0] = r[1] & POOL[113];
    r[2] = {
        let (t, ma, mb) = (POOL[114], POOL[115], POOL[116]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[2];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[117];
    r[0] = r[5] ^ r[3];
    r[2] = r[4] ^ r[0];
    r[0] = r[1] & POOL[118];
    r[4] = {
        let (t, ma, mb) = (POOL[119], POOL[120], POOL[121]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[4];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[122];
    r[0] = r[5] ^ r[3];
    r[4] = r[2] ^ r[0];
    r[0] = r[1] & POOL[123];
    r[2] = {
        let (t, ma, mb) = (POOL[124], POOL[125], POOL[126]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[2];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[127];
    r[0] = r[5] ^ r[3];
    r[2] = r[4] ^ r[0];
    r[0] = r[1] & POOL[128];
    r[4] = {
        let (t, ma, mb) = (POOL[129], POOL[130], POOL[131]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[4];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[132];
    r[0] = r[5] ^ r[3];
    r[4] = r[2] ^ r[0];
    r[0] = r[1] & POOL[133];
    r[2] = {
        let (t, ma, mb) = (POOL[134], POOL[135], POOL[136]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[2];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[137];
    r[0] = r[5] ^ r[3];
    r[2] = r[4] ^ r[0];
    r[0] = r[1] & POOL[138];
    r[4] = {
        let (t, ma, mb) = (POOL[139], POOL[140], POOL[141]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[4];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[142];
    r[0] = r[5] ^ r[3];
    r[4] = r[2] ^ r[0];
    r[0] = r[1] & POOL[143];
    r[2] = {
        let (t, ma, mb) = (POOL[144], POOL[145], POOL[146]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[2];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[147];
    r[0] = r[5] ^ r[3];
    r[2] = r[4] ^ r[0];
    r[0] = r[1] & POOL[148];
    r[4] = {
        let (t, ma, mb) = (POOL[149], POOL[150], POOL[151]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[4];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[152];
    r[0] = r[5] ^ r[3];
    r[4] = r[2] ^ r[0];
    r[0] = r[1] & POOL[153];
    r[1] = {
        let (t, ma, mb) = (POOL[154], POOL[155], POOL[156]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[1];
    r[3] = r[5].rotate_left(1);
    r[5] = r[6] & POOL[157];
    r[1] = r[5] ^ r[3];
    r[5] = r[4] ^ r[1];
    r[5] ^ POOL[158]
}
