// Generated by `cargo run --bin regen_fixtures` — do not edit manually.
pub fn add32_demo(a: u32, b: u32) -> u32 {
    const POOL: &[u32] = &[
        0xcd2c6f7f,
        0xbb2a3fb2,
        0x070f4649,
        0xcd2c6f7f,
        0xbb2a3fb2,
        0x00000001,
        0x00000001,
        0x00000002,
        0x00000002,
        0xc6017c94,
        0x00000000,
        0x00000002,
        0x00000004,
        0x00000004,
        0xcf310a12,
        0x00000004,
        0x8c02f92d,
        0x00000008,
        0x00000008,
        0x069dc10a,
        0x00000008,
        0x9e62142d,
        0x00000010,
        0x00000010,
        0xabe5f6d0,
        0x00000000,
        0x0d3b8214,
        0x00000020,
        0x00000020,
        0x958b761d,
        0x00000000,
        0x57cbed81,
        0x00000040,
        0x00000040,
        0xdee17b51,
        0x00000040,
        0x2b16ec7b,
        0x00000080,
        0x00000080,
        0x431d9dd4,
        0x00000080,
        0xbdc2f6a3,
        0x00000100,
        0x00000100,
        0x1f71c422,
        0x00000000,
        0x863b3aa8,
        0x00000200,
        0x00000200,
        0xc5a0ef11,
        0x00000000,
        0x3ee38a44,
        0x00000400,
        0x00000400,
        0x12037913,
        0x00000000,
        0x8b41de23,
        0x00000800,
        0x00000800,
        0x37fc854f,
        0x00000000,
        0x2406f226,
        0x00001000,
        0x00001000,
        0xc9ff71c7,
        0x00001000,
        0x6ff91a9e,
        0x00002000,
        0x00002000,
        0xcb30ce1a,
        0x00000000,
        0x93fec38f,
        0x00004000,
        0x00004000,
        0x9e0d3fac,
        0x00004000,
        0x9661dc35,
        0x00008000,
        0x00008000,
        0xbfd4a4ae,
        0x00000000,
        0x3c1a7f59,
        0x00010000,
        0x00010000,
        0x87b83854,
        0x00000000,
        0x7fa9495d,
        0x00020000,
        0x00020000,
        0xf80e4de3,
        0x00020000,
        0x0f7270a9,
        0x00040000,
        0x00040000,
        0xd99c7f7e,
        0x00040000,
        0xf01c9bc7,
        0x00080000,
        0x00080000,
        0xff0ea77d,
        0x00000000,
        0xb338fefd,
        0x00100000,
        0x00100000,
        0x48501800,
        0x00000000,
        0xfe1d4efb,
        0x00200000,
        0x00200000,
        0x23ae2c7b,
        0x00000000,
        0x90a03000,
        0x00400000,
        0x00400000,
        0x0bd4b7bb,
        0x00000000,
        0x471c58f6,
        0x00800000,
        0x00800000,
        0x1ce4b87b,
        0x00000000,
        0x17a96f76,
        0x01000000,
        0x01000000,
        0xfd960655,
        0x00000000,
        0x39c970f6,
        0x02000000,
        0x02000000,
        0xf4ff78ef,
        0x02000000,
        0xfb2c0cab,
        0x04000000,
        0x04000000,
        0x34bb13f0,
        0x04000000,
        0xe9fef1df,
        0x08000000,
        0x08000000,
        0x0ca57b62,
        0x00000000,
        0x617627e0,
        0x10000000,
        0x10000000,
        0x6e3bd6a2,
        0x10000000,
        0x094af6c4,
        0x20000000,
        0x20000000,
        0x6cfacf84,
        0x20000000,
        0xdc77ad44,
        0x40000000,
        0x40000000,
        0xe6e1329a,
        0x40000000,
        0xd9f59f08,
        0x80000000,
        0xef31307c,
    ];
    let mut r = [0u32; 220];
    r[0] = a ^ POOL[0];
    r[1] = b ^ POOL[1];
    r[2] = {
        let (t, ma, mb) = (POOL[2], POOL[3], POOL[4]);
        let mut z = t;
        z ^= r[0] & mb;
        z ^= r[1] & ma;
        z ^= r[0] & r[1];
        z
    };
    r[3] = r[0] ^ r[1];
    r[4] = r[3] & POOL[5];
    r[5] = r[2] & POOL[6];
    r[6] = r[5].rotate_left(1);
    r[7] = r[3] & POOL[7];
    r[8] = r[7] ^ r[6];
    r[9] = r[4] ^ r[8];
    r[10] = r[2] & POOL[8];
    r[11] = {
        let (t, ma, mb) = (POOL[9], POOL[10], POOL[11]);
        let mut z = t;
        z ^= r[7] & mb;
        z ^= r[6] & ma;
        z ^= r[7] & r[6];
        z
    };
    r[12] = r[10] ^ r[11];
    r[13] = r[12].rotate_left(1);
    r[14] = r[3] & POOL[12];
    r[15] = r[14] ^ r[13];
    r[16] = r[9] ^ r[15];
    r[17] = r[2] & POOL[13];
    r[18] = {
        let (t, ma, mb) = (POOL[14], POOL[15], POOL[16]);
        let mut z = t;
        z ^= r[14] & mb;
        z ^= r[13] & ma;
        z ^= r[14] & r[13];
        z
    };
    r[19] = r[17] ^ r[18];
    r[20] = r[19].rotate_left(1);
    r[21] = r[3] & POOL[17];
    r[22] = r[21] ^ r[20];
    r[23] = r[16] ^ r[22];
    r[24] = r[2] & POOL[18];
    r[25] = {
        let (t, ma, mb) = (POOL[19], POOL[20], POOL[21]);
        let mut z = t;
        z ^= r[21] & mb;
        z ^= r[20] & ma;
        z ^= r[21] & r[20];
        z
    };
    r[26] = r[24] ^ r[25];
    r[27] = r[26].rotate_left(1);
    r[28] = r[3] & POOL[22];
    r[29] = r[28] ^ r[27];
    r[30] = r[23] ^ r[29];
    r[31] = r[2] & POOL[23];
    r[32] = {
        let (t, ma, mb) = (POOL[24], POOL[25], POOL[26]);
        let mut z = t;
        z ^= r[28] & mb;
        z ^= r[27] & ma;
        z ^= r[28] & r[27];
        z
    };
    r[33] = r[31] ^ r[32];
    r[34] = r[33].rotate_left(1);
    r[35] = r[3] & POOL[27];
    r[36] = r[35] ^ r[34];
    r[37] = r[30] ^ r[36];
    r[38] = r[2] & POOL[28];
    r[39] = {
        let (t, ma, mb) = (POOL[29], POOL[30], POOL[31]);
        let mut z = t;
        z ^= r[35] & mb;
        z ^= r[34] & ma;
        z ^= r[35] & r[34];
        z
    };
    r[40] = r[38] ^ r[39];
    r[41] = r[40].rotate_left(1);
    r[42] = r[3] & POOL[32];
    r[43] = r[42] ^ r[41];
    r[44] = r[37] ^ r[43];
    r[45] = r[2] & POOL[33];
    r[46] = {
        let (t, ma, mb) = (POOL[34], POOL[35], POOL[36]);
        let mut z = t;
        z ^= r[42] & mb;
        z ^= r[41] & ma;
        z ^= r[42] & r[41];
        z
    };
    r[47] = r[45] ^ r[46];
    r[48] = r[47].rotate_left(1);
    r[49] = r[3] & POOL[37];
    r[50] = r[49] ^ r[48];
    r[51] = r[44] ^ r[50];
    r[52] = r[2] & POOL[38];
    r[53] = {
        let (t, ma, mb) = (POOL[39], POOL[40], POOL[41]);
        let mut z = t;
        z ^= r[49] & mb;
        z ^= r[48] & ma;
        z ^= r[49] & r[48];
        z
    };
    r[54] = r[52] ^ r[53];
    r[55] = r[54].rotate_left(1);
    r[56] = r[3] & POOL[42];
    r[57] = r[56] ^ r[55];
    r[58] = r[51] ^ r[57];
    r[59] = r[2] & POOL[43];
    r[60] = {
        let (t, ma, mb) = (POOL[44], POOL[45], POOL[46]);
        let mut z = t;
        z ^= r[56] & mb;
        z ^= r[55] & ma;
        z ^= r[56] & r[55];
        z
    };
    r[61] = r[59] ^ r[60];
    r[62] = r[61].rotate_left(1);
    r[63] = r[3] & POOL[47];
    r[64] = r[63] ^ r[62];
    r[65] = r[58] ^ r[64];
    r[66] = r[2] & POOL[48];
    r[67] = {
        let (t, ma, mb) = (POOL[49], POOL[50], POOL[51]);
        let mut z = t;
        z ^= r[63] & mb;
        z ^= r[62] & ma;
        z ^= r[63] & r[62];
        z
    };
    r[68] = r[66] ^ r[67];
    r[69] = r[68].rotate_left(1);
    r[70] = r[3] & POOL[52];
    r[71] = r[70] ^ r[69];
    r[72] = r[65] ^ r[71];
    r[73] = r[2] & POOL[53];
    r[74] = {
        let (t, ma, mb) = (POOL[54], POOL[55], POOL[56]);
        let mut z = t;
        z ^= r[70] & mb;
        z ^= r[69] & ma;
        z ^= r[70] & r[69];
        z
    };
    r[75] = r[73] ^ r[74];
    r[76] = r[75].rotate_left(1);
    r[77] = r[3] & POOL[57];
    r[78] = r[77] ^ r[76];
    r[79] = r[72] ^ r[78];
    r[80] = r[2] & POOL[58];
    r[81] = {
        let (t, ma, mb) = (POOL[59], POOL[60], POOL[61]);
        let mut z = t;
        z ^= r[77] & mb;
        z ^= r[76] & ma;
        z ^= r[77] & r[76];
        z
    };
    r[82] = r[80] ^ r[81];
    r[83] = r[82].rotate_left(1);
    r[84] = r[3] & POOL[62];
    r[85] = r[84] ^ r[83];
    r[86] = r[79] ^ r[85];
    r[87] = r[2] & POOL[63];
    r[88] = {
        let (t, ma, mb) = (POOL[64], POOL[65], POOL[66]);
        let mut z = t;
        z ^= r[84] & mb;
        z ^= r[83] & ma;
        z ^= r[84] & r[83];
        z
    };
    r[89] = r[87] ^ r[88];
    r[90] = r[89].rotate_left(1);
    r[91] = r[3] & POOL[67];
    r[92] = r[91] ^ r[90];
    r[93] = r[86] ^ r[92];
    r[94] = r[2] & POOL[68];
    r[95] = {
        let (t, ma, mb) = (POOL[69], POOL[70], POOL[71]);
        let mut z = t;
        z ^= r[91] & mb;
        z ^= r[90] & ma;
        z ^= r[91] & r[90];
        z
    };
    r[96] = r[94] ^ r[95];
    r[97] = r[96].rotate_left(1);
    r[98] = r[3] & POOL[72];
    r[99] = r[98] ^ r[97];
    r[100] = r[93] ^ r[99];
    r[101] = r[2] & POOL[73];
    r[102] = {
        let (t, ma, mb) = (POOL[74], POOL[75], POOL[76]);
        let mut z = t;
        z ^= r[98] & mb;
        z ^= r[97] & ma;
        z ^= r[98] & r[97];
        z
    };
    r[103] = r[101] ^ r[102];
    r[104] = r[103].rotate_left(1);
    r[105] = r[3] & POOL[77];
    r[106] = r[105] ^ r[104];
    r[107] = r[100] ^ r[106];
    r[108] = r[2] & POOL[78];
    r[109] = {
        let (t, ma, mb) = (POOL[79], POOL[80], POOL[81]);
        let mut z = t;
        z ^= r[105] & mb;
        z ^= r[104] & ma;
        z ^= r[105] & r[104];
        z
    };
    r[110] = r[108] ^ r[109];
    r[111] = r[110].rotate_left(1);
    r[112] = r[3] & POOL[82];
    r[113] = r[112] ^ r[111];
    r[114] = r[107] ^ r[113];
    r[115] = r[2] & POOL[83];
    r[116] = {
        let (t, ma, mb) = (POOL[84], POOL[85], POOL[86]);
        let mut z = t;
        z ^= r[112] & mb;
        z ^= r[111] & ma;
        z ^= r[112] & r[111];
        z
    };
    r[117] = r[115] ^ r[116];
    r[118] = r[117].rotate_left(1);
    r[119] = r[3] & POOL[87];
    r[120] = r[119] ^ r[118];
    r[121] = r[114] ^ r[120];
    r[122] = r[2] & POOL[88];
    r[123] = {
        let (t, ma, mb) = (POOL[89], POOL[90], POOL[91]);
        let mut z = t;
        z ^= r[119] & mb;
        z ^= r[118] & ma;
        z ^= r[119] & r[118];
        z
    };
    r[124] = r[122] ^ r[123];
    r[125] = r[124].rotate_left(1);
    r[126] = r[3] & POOL[92];
    r[127] = r[126] ^ r[125];
    r[128] = r[121] ^ r[127];
    r[129] = r[2] & POOL[93];
    r[130] = {
        let (t, ma, mb) = (POOL[94], POOL[95], POOL[96]);
        let mut z = t;
        z ^= r[126] & mb;
        z ^= r[125] & ma;
        z ^= r[126] & r[125];
        z
    };
    r[131] = r[129] ^ r[130];
    r[132] = r[131].rotate_left(1);
    r[133] = r[3] & POOL[97];
    r[134] = r[133] ^ r[132];
    r[135] = r[128] ^ r[134];
    r[136] = r[2] & POOL[98];
    r[137] = {
        let (t, ma, mb) = (POOL[99], POOL[100], POOL[101]);
        let mut z = t;
        z ^= r[133] & mb;
        z ^= r[132] & ma;
        z ^= r[133] & r[132];
        z
    };
    r[138] = r[136] ^ r[137];
    r[139] = r[138].rotate_left(1);
    r[140] = r[3] & POOL[102];
    r[141] = r[140] ^ r[139];
    r[142] = r[135] ^ r[141];
    r[143] = r[2] & POOL[103];
    r[144] = {
        let (t, ma, mb) = (POOL[104], POOL[105], POOL[106]);
        let mut z = t;
        z ^= r[140] & mb;
        z ^= r[139] & ma;
        z ^= r[140] & r[139];
        z
    };
    r[145] = r[143] ^ r[144];
    r[146] = r[145].rotate_left(1);
    r[147] = r[3] & POOL[107];
    r[148] = r[147] ^ r[146];
    r[149] = r[142] ^ r[148];
    r[150] = r[2] & POOL[108];
    r[151] = {
        let (t, ma, mb) = (POOL[109], POOL[110], POOL[111]);
        let mut z = t;
        z ^= r[147] & mb;
        z ^= r[146] & ma;
        z ^= r[147] & r[146];
        z
    };
    r[152] = r[150] ^ r[151];
    r[153] = r[152].rotate_left(1);
    r[154] = r[3] & POOL[112];
    r[155] = r[154] ^ r[153];
    r[156] = r[149] ^ r[155];
    r[157] = r[2] & POOL[113];
    r[158] = {
        let (t, ma, mb) = (POOL[114], POOL[115], POOL[116]);
        let mut z = t;
        z ^= r[154] & mb;
        z ^= r[153] & ma;
        z ^= r[154] & r[153];
        z
    };
    r[159] = r[157] ^ r[158];
    r[160] = r[159].rotate_left(1);
    r[161] = r[3] & POOL[117];
    r[162] = r[161] ^ r[160];
    r[163] = r[156] ^ r[162];
    r[164] = r[2] & POOL[118];
    r[165] = {
        let (t, ma, mb) = (POOL[119], POOL[120], POOL[121]);
        let mut z = t;
        z ^= r[161] & mb;
        z ^= r[160] & ma;
        z ^= r[161] & r[160];
        z
    };
    r[166] = r[164] ^ r[165];
    r[167] = r[166].rotate_left(1);
    r[168] = r[3] & POOL[122];
    r[169] = r[168] ^ r[167];
    r[170] = r[163] ^ r[169];
    r[171] = r[2] & POOL[123];
    r[172] = {
        let (t, ma, mb) = (POOL[124], POOL[125], POOL[126]);
        let mut z = t;
        z ^= r[168] & mb;
        z ^= r[167] & ma;
        z ^= r[168] & r[167];
        z
    };
    r[173] = r[171] ^ r[172];
    r[174] = r[173].rotate_left(1);
    r[175] = r[3] & POOL[127];
    r[176] = r[175] ^ r[174];
    r[177] = r[170] ^ r[176];
    r[178] = r[2] & POOL[128];
    r[179] = {
        let (t, ma, mb) = (POOL[129], POOL[130], POOL[131]);
        let mut z = t;
        z ^= r[175] & mb;
        z ^= r[174] & ma;
        z ^= r[175] & r[174];
        z
    };
    r[180] = r[178] ^ r[179];
    r[181] = r[180].rotate_left(1);
    r[182] = r[3] & POOL[132];
    r[183] = r[182] ^ r[181];
    r[184] = r[177] ^ r[183];
    r[185] = r[2] & POOL[133];
    r[186] = {
        let (t, ma, mb) = (POOL[134], POOL[135], POOL[136]);
        let mut z = t;
        z ^= r[182] & mb;
        z ^= r[181] & ma;
        z ^= r[182] & r[181];
        z
    };
    r[187] = r[185] ^ r[186];
    r[188] = r[187].rotate_left(1);
    r[189] = r[3] & POOL[137];
    r[190] = r[189] ^ r[188];
    r[191] = r[184] ^ r[190];
    r[192] = r[2] & POOL[138];
    r[193] = {
        let (t, ma, mb) = (POOL[139], POOL[140], POOL[141]);
        let mut z = t;
        z ^= r[189] & mb;
        z ^= r[188] & ma;
        z ^= r[189] & r[188];
        z
    };
    r[194] = r[192] ^ r[193];
    r[195] = r[194].rotate_left(1);
    r[196] = r[3] & POOL[142];
    r[197] = r[196] ^ r[195];
    r[198] = r[191] ^ r[197];
    r[199] = r[2] & POOL[143];
    r[200] = {
        let (t, ma, mb) = (POOL[144], POOL[145], POOL[146]);
        let mut z = t;
        z ^= r[196] & mb;
        z ^= r[195] & ma;
        z ^= r[196] & r[195];
        z
    };
    r[201] = r[199] ^ r[200];
    r[202] = r[201].rotate_left(1);
    r[203] = r[3] & POOL[147];
    r[204] = r[203] ^ r[202];
    r[205] = r[198] ^ r[204];
    r[206] = r[2] & POOL[148];
    r[207] = {
        let (t, ma, mb) = (POOL[149], POOL[150], POOL[151]);
        let mut z = t;
        z ^= r[203] & mb;
        z ^= r[202] & ma;
        z ^= r[203] & r[202];
        z
    };
    r[208] = r[206] ^ r[207];
    r[209] = r[208].rotate_left(1);
    r[210] = r[3] & POOL[152];
    r[211] = r[210] ^ r[209];
    r[212] = r[205] ^ r[211];
    r[213] = r[2] & POOL[153];
    r[214] = {
        let (t, ma, mb) = (POOL[154], POOL[155], POOL[156]);
        let mut z = t;
        z ^= r[210] & mb;
        z ^= r[209] & ma;
        z ^= r[210] & r[209];
        z
    };
    r[215] = r[213] ^ r[214];
    r[216] = r[215].rotate_left(1);
    r[217] = r[3] & POOL[157];
    r[218] = r[217] ^ r[216];
    r[219] = r[212] ^ r[218];
    r[219] ^ POOL[158]
}
