// Generated by `cargo run --bin regen_fixtures` — do not edit manually.
pub const ROTATION_TAG: u32 = 0xbf6822f7;
pub fn chacha_qr(a: u32, b: u32, c: u32, d: u32) -> u32 {
    const POOL: &[u32] = &[
        0xcd2c6f7f,
        0xbb2a3fb2,
        0x070f4649,
        0xcd2c6f7f,
        0xbb2a3fb2,
        0x00000001,
        0x00000001,
        0x00000002,
        0x00000002,
        0xc6017c94,
        0x00000000,
        0x00000002,
        0x00000004,
        0x00000004,
        0xcf310a12,
        0x00000004,
        0x8c02f92d,
        0x00000008,
        0x00000008,
        0x069dc10a,
        0x00000008,
        0x9e62142d,
        0x00000010,
        0x00000010,
        0xabe5f6d0,
        0x00000000,
        0x0d3b8214,
        0x00000020,
        0x00000020,
        0x958b761d,
        0x00000000,
        0x57cbed81,
        0x00000040,
        0x00000040,
        0xdee17b51,
        0x00000040,
        0x2b16ec7b,
        0x00000080,
        0x00000080,
        0x431d9dd4,
        0x00000080,
        0xbdc2f6a3,
        0x00000100,
        0x00000100,
        0x1f71c422,
        0x00000000,
        0x863b3aa8,
        0x00000200,
        0x00000200,
        0xc5a0ef11,
        0x00000000,
        0x3ee38a44,
        0x00000400,
        0x00000400,
        0x12037913,
        0x00000000,
        0x8b41de23,
        0x00000800,
        0x00000800,
        0x37fc854f,
        0x00000000,
        0x2406f226,
        0x00001000,
        0x00001000,
        0xc9ff71c7,
        0x00001000,
        0x6ff91a9e,
        0x00002000,
        0x00002000,
        0xcb30ce1a,
        0x00000000,
        0x93fec38f,
        0x00004000,
        0x00004000,
        0x9e0d3fac,
        0x00004000,
        0x9661dc35,
        0x00008000,
        0x00008000,
        0xbfd4a4ae,
        0x00000000,
        0x3c1a7f59,
        0x00010000,
        0x00010000,
        0x87b83854,
        0x00000000,
        0x7fa9495d,
        0x00020000,
        0x00020000,
        0xf80e4de3,
        0x00020000,
        0x0f7270a9,
        0x00040000,
        0x00040000,
        0xd99c7f7e,
        0x00040000,
        0xf01c9bc7,
        0x00080000,
        0x00080000,
        0xff0ea77d,
        0x00000000,
        0xb338fefd,
        0x00100000,
        0x00100000,
        0x48501800,
        0x00000000,
        0xfe1d4efb,
        0x00200000,
        0x00200000,
        0x23ae2c7b,
        0x00000000,
        0x90a03000,
        0x00400000,
        0x00400000,
        0x0bd4b7bb,
        0x00000000,
        0x471c58f6,
        0x00800000,
        0x00800000,
        0x1ce4b87b,
        0x00000000,
        0x17a96f76,
        0x01000000,
        0x01000000,
        0xfd960655,
        0x00000000,
        0x39c970f6,
        0x02000000,
        0x02000000,
        0xf4ff78ef,
        0x02000000,
        0xfb2c0cab,
        0x04000000,
        0x04000000,
        0x34bb13f0,
        0x04000000,
        0xe9fef1df,
        0x08000000,
        0x08000000,
        0x0ca57b62,
        0x00000000,
        0x617627e0,
        0x10000000,
        0x10000000,
        0x6e3bd6a2,
        0x10000000,
        0x094af6c4,
        0x20000000,
        0x20000000,
        0x6cfacf84,
        0x20000000,
        0xdc77ad44,
        0x40000000,
        0x40000000,
        0xe6e1329a,
        0x40000000,
        0xd9f59f08,
        0x80000000,
        0x75e88c63,
        0x30f0a328,
        0xfddcf67d,
        0x75e88c63,
        0x9354dfc1,
        0x00000001,
        0x00000001,
        0x00000002,
        0x00000002,
        0xfed54eba,
        0x00000002,
        0x00000000,
        0x00000004,
        0x00000004,
        0x3a1f55f0,
        0x00000000,
        0xfdaa9d75,
        0x00000008,
        0x00000008,
        0x65781cfd,
        0x00000000,
        0x743eabe8,
        0x00000010,
        0x00000010,
        0x8f3066bc,
        0x00000000,
        0xcaf039ea,
        0x00000020,
        0x00000020,
        0xaf976aeb,
        0x00000020,
        0x1e60cd59,
        0x00000040,
        0x00000040,
        0x27c7951f,
        0x00000000,
        0x5f2ed597,
        0x00000080,
        0x00000080,
        0xb892a064,
        0x00000080,
        0x4f8f2a3e,
        0x00000100,
        0x00000100,
        0xd5e34c79,
        0x00000100,
        0x712540c9,
        0x00000200,
        0x00000200,
        0x76ef4fb1,
        0x00000200,
        0xabc698f3,
        0x00000400,
        0x00000400,
        0x345f0997,
        0x00000000,
        0xedde9b62,
        0x00000800,
        0x00000800,
        0x135f3ef3,
        0x00000000,
        0x68be132e,
        0x00001000,
        0x00001000,
        0x80cd14a8,
        0x00001000,
        0x26be6de6,
        0x00002000,
        0x00002000,
        0xe15e4e8d,
        0x00000000,
        0x019a0951,
        0x00004000,
        0x00004000,
        0xa343cbd0,
        0x00004000,
        0xc2bcdd1b,
        0x00008000,
        0x00008000,
        0xbf5704d8,
        0x00000000,
        0x468797a1,
        0x00010000,
        0x00010000,
        0x7a95e009,
        0x00000000,
        0x7eae09b1,
        0x00020000,
        0x00020000,
        0x582b922f,
        0x00000000,
        0xf52bc012,
        0x00040000,
        0x00040000,
        0xe04296e7,
        0x00040000,
        0xb057245e,
        0x00080000,
        0x00080000,
        0xcb29252a,
        0x00080000,
        0xc0852dcf,
        0x00100000,
        0x00100000,
        0xdee3997c,
        0x00100000,
        0x96424a55,
        0x00200000,
        0x00200000,
        0xbb420156,
        0x00200000,
        0xbde732f9,
        0x00400000,
        0x00400000,
        0x102ff028,
        0x00000000,
        0x76c402ad,
        0x00800000,
        0x00800000,
        0xecdca315,
        0x00800000,
        0x205fe050,
        0x01000000,
        0x01000000,
        0xfca4dc38,
        0x00000000,
        0xd8b9462b,
        0x02000000,
        0x02000000,
        0x295b5373,
        0x02000000,
        0xf949b871,
        0x04000000,
        0x04000000,
        0x37800b8b,
        0x04000000,
        0x52b6a6e6,
        0x08000000,
        0x08000000,
        0x6fdc7e07,
        0x00000000,
        0x67001716,
        0x10000000,
        0x10000000,
        0xfa202be2,
        0x00000000,
        0xcfb8fc0e,
        0x20000000,
        0x20000000,
        0x6c0bcc72,
        0x20000000,
        0xf44057c5,
        0x40000000,
        0x40000000,
        0xaadd98ee,
        0x40000000,
        0xd81798e4,
        0x80000000,
        0x206390a9,
        0xef31307c,
        0x438d7c8d,
        0x00000001,
        0x00000001,
        0x00000002,
        0x00000002,
        0xad5d3511,
        0x00000000,
        0x00000002,
        0x00000004,
        0x00000004,
        0x610e6994,
        0x00000000,
        0x5aba6a23,
        0x00000008,
        0x00000008,
        0x03d8ae10,
        0x00000000,
        0xc21cd320,
        0x00000010,
        0x00000010,
        0xd192ea97,
        0x00000010,
        0x07b15c20,
        0x00000020,
        0x00000020,
        0x11b8821a,
        0x00000020,
        0xa325d52f,
        0x00000040,
        0x00000040,
        0xdb1dfde3,
        0x00000040,
        0x23710434,
        0x00000080,
        0x00000080,
        0x9e3f61a8,
        0x00000080,
        0xb63bfbc7,
        0x00000100,
        0x00000100,
        0xb36998ad,
        0x00000000,
        0x3c7ec351,
        0x00000200,
        0x00000200,
        0x9d1ffa92,
        0x00000000,
        0x66d3315b,
        0x00000400,
        0x00000400,
        0xabf1ba91,
        0x00000400,
        0x3a3ff525,
        0x00000800,
        0x00000800,
        0xc9055e62,
        0x00000800,
        0x57e37d23,
        0x00001000,
        0x00001000,
        0x532fc768,
        0x00000000,
        0x920aacc5,
        0x00002000,
        0x00002000,
        0xaa77ac12,
        0x00000000,
        0xa65f8ed0,
        0x00004000,
        0x00004000,
        0xdd58898e,
        0x00004000,
        0x54ef1825,
        0x00008000,
        0x00008000,
        0x159ba8db,
        0x00000000,
        0xbab1131d,
        0x00010000,
        0x00010000,
        0xd0efd947,
        0x00000000,
        0x2b3651b6,
        0x00020000,
        0x00020000,
        0x157eb310,
        0x00000000,
        0xa1dfb28f,
        0x00040000,
        0x00040000,
        0xf46bbc6e,
        0x00040000,
        0x2af96620,
        0x00080000,
        0x00080000,
        0x84ca4d1a,
        0x00080000,
        0xe8d778dd,
        0x00100000,
        0x00100000,
        0xdc7b7cd6,
        0x00100000,
        0x09949a35,
        0x00200000,
        0x00200000,
        0xc0c08aa8,
        0x00200000,
        0xb8d6f9ad,
        0x00400000,
        0x00400000,
        0x410142c3,
        0x00000000,
        0x81c11551,
        0x00800000,
        0x00800000,
        0xdea674d5,
        0x00800000,
        0x82828586,
        0x01000000,
        0x01000000,
        0x2a6f3545,
        0x00000000,
        0xbc4ce9ab,
        0x02000000,
        0x02000000,
        0x166d4584,
        0x00000000,
        0x56de6a8a,
        0x04000000,
        0x04000000,
        0x3c59c49b,
        0x04000000,
        0x28da8b08,
        0x08000000,
        0x08000000,
        0x51e3238a,
        0x08000000,
        0x78b38936,
        0x10000000,
        0x10000000,
        0xe5db98b8,
        0x00000000,
        0xb3c64714,
        0x20000000,
        0x20000000,
        0x2ff64e1b,
        0x20000000,
        0xcbb73171,
        0x40000000,
        0x40000000,
        0xe299eb10,
        0x00000000,
        0x1fec9c36,
        0x80000000,
        0xf402c719,
        0x73fe0765,
        0x79bc0a19,
        0x00000001,
        0x00000001,
        0x00000002,
        0x00000002,
        0x9f85f25d,
        0x00000000,
        0x00000000,
        0x00000004,
        0x00000004,
        0xfa077d26,
        0x00000004,
        0x3f0be4bb,
        0x00000008,
        0x00000008,
        0x69194a0a,
        0x00000008,
        0xf40efa4d,
        0x00000010,
        0x00000010,
        0x4389962b,
        0x00000010,
        0xd2329414,
        0x00000020,
        0x00000020,
        0x6742ac36,
        0x00000020,
        0x87132c56,
        0x00000040,
        0x00000040,
        0x400a2150,
        0x00000040,
        0xce85586c,
        0x00000080,
        0x00000080,
        0x7bb0adce,
        0x00000000,
        0x80144220,
        0x00000100,
        0x00000100,
        0xfc2698b7,
        0x00000100,
        0xf7615b9c,
        0x00000200,
        0x00000200,
        0xffd75ad9,
        0x00000000,
        0xf84d316f,
        0x00000400,
        0x00000400,
        0xaa7fd7f5,
        0x00000400,
        0xffaeb5b3,
        0x00000800,
        0x00000800,
        0x18dfda7d,
        0x00000800,
        0x54ffafeb,
        0x00001000,
        0x00001000,
        0xac0c9449,
        0x00000000,
        0x31bfa4fa,
        0x00002000,
        0x00002000,
        0x9fa708d2,
        0x00000000,
        0x58192893,
        0x00004000,
        0x00004000,
        0xcab2a0b3,
        0x00000000,
        0x3f4e11a5,
        0x00008000,
        0x00008000,
        0xb250cb87,
        0x00000000,
        0x9565c167,
        0x00010000,
        0x00010000,
        0x4ae55c63,
        0x00000000,
        0x64a0970f,
        0x00020000,
        0x00020000,
        0xcd8057a1,
        0x00020000,
        0x95cab8c6,
        0x00040000,
        0x00040000,
        0xa26c9c2b,
        0x00000000,
        0x9b00af43,
        0x00080000,
        0x00080000,
        0xea01252b,
        0x00000000,
        0x44d13857,
        0x00100000,
        0x00100000,
        0x08c8f3bd,
        0x00000000,
        0xd4124a57,
        0x00200000,
        0x00200000,
        0xeab81afa,
        0x00000000,
        0x11b1e77a,
        0x00400000,
        0x00400000,
        0x15661793,
        0x00400000,
        0xd53035f5,
        0x00800000,
        0x00800000,
        0x03fbe027,
        0x00000000,
        0x2acc2f26,
        0x01000000,
        0x01000000,
        0x318ce55a,
        0x00000000,
        0x06f7c04e,
        0x02000000,
        0x02000000,
        0xbf4da8ff,
        0x02000000,
        0x6119cab4,
        0x04000000,
        0x04000000,
        0xa7e71c18,
        0x00000000,
        0x7e9b51ff,
        0x08000000,
        0x08000000,
        0xbe1bb62a,
        0x08000000,
        0x47ce3831,
        0x10000000,
        0x10000000,
        0x94da8bfb,
        0x00000000,
        0x7c376c55,
        0x20000000,
        0x20000000,
        0x0f7c0b95,
        0x00000000,
        0x29b517f7,
        0x40000000,
        0x40000000,
        0x2fcfbadc,
        0x00000000,
        0x1ef8172a,
        0x80000000,
        0x08669621,
    ];
    let mut r = [0u32; 10];
    r[3] = a ^ POOL[0];
    r[5] = b ^ POOL[1];
    r[4] = {
        let (t, ma, mb) = (POOL[2], POOL[3], POOL[4]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[5] & ma;
        z ^= r[3] & r[5];
        z
    };
    r[6] = r[3] ^ r[5];
    r[3] = r[6] & POOL[5];
    r[9] = r[4] & POOL[6];
    r[1] = r[9].rotate_left(1);
    r[9] = r[6] & POOL[7];
    r[2] = r[9] ^ r[1];
    r[0] = r[3] ^ r[2];
    r[3] = r[4] & POOL[8];
    r[2] = {
        let (t, ma, mb) = (POOL[9], POOL[10], POOL[11]);
        let mut z = t;
        z ^= r[9] & mb;
        z ^= r[1] & ma;
        z ^= r[9] & r[1];
        z
    };
    r[9] = r[3] ^ r[2];
    r[3] = r[9].rotate_left(1);
    r[9] = r[6] & POOL[12];
    r[1] = r[9] ^ r[3];
    r[2] = r[0] ^ r[1];
    r[1] = r[4] & POOL[13];
    r[0] = {
        let (t, ma, mb) = (POOL[14], POOL[15], POOL[16]);
        let mut z = t;
        z ^= r[9] & mb;
        z ^= r[3] & ma;
        z ^= r[9] & r[3];
        z
    };
    r[3] = r[1] ^ r[0];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[17];
    r[1] = r[3] ^ r[9];
    r[0] = r[2] ^ r[1];
    r[1] = r[4] & POOL[18];
    r[2] = {
        let (t, ma, mb) = (POOL[19], POOL[20], POOL[21]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[2];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[22];
    r[1] = r[3] ^ r[9];
    r[2] = r[0] ^ r[1];
    r[1] = r[4] & POOL[23];
    r[0] = {
        let (t, ma, mb) = (POOL[24], POOL[25], POOL[26]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[0];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[27];
    r[1] = r[3] ^ r[9];
    r[0] = r[2] ^ r[1];
    r[1] = r[4] & POOL[28];
    r[2] = {
        let (t, ma, mb) = (POOL[29], POOL[30], POOL[31]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[2];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[32];
    r[1] = r[3] ^ r[9];
    r[2] = r[0] ^ r[1];
    r[1] = r[4] & POOL[33];
    r[0] = {
        let (t, ma, mb) = (POOL[34], POOL[35], POOL[36]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[0];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[37];
    r[1] = r[3] ^ r[9];
    r[0] = r[2] ^ r[1];
    r[1] = r[4] & POOL[38];
    r[2] = {
        let (t, ma, mb) = (POOL[39], POOL[40], POOL[41]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[2];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[42];
    r[1] = r[3] ^ r[9];
    r[2] = r[0] ^ r[1];
    r[1] = r[4] & POOL[43];
    r[0] = {
        let (t, ma, mb) = (POOL[44], POOL[45], POOL[46]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[0];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[47];
    r[1] = r[3] ^ r[9];
    r[0] = r[2] ^ r[1];
    r[1] = r[4] & POOL[48];
    r[2] = {
        let (t, ma, mb) = (POOL[49], POOL[50], POOL[51]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[2];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[52];
    r[1] = r[3] ^ r[9];
    r[2] = r[0] ^ r[1];
    r[1] = r[4] & POOL[53];
    r[0] = {
        let (t, ma, mb) = (POOL[54], POOL[55], POOL[56]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[0];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[57];
    r[1] = r[3] ^ r[9];
    r[0] = r[2] ^ r[1];
    r[1] = r[4] & POOL[58];
    r[2] = {
        let (t, ma, mb) = (POOL[59], POOL[60], POOL[61]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[2];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[62];
    r[1] = r[3] ^ r[9];
    r[2] = r[0] ^ r[1];
    r[1] = r[4] & POOL[63];
    r[0] = {
        let (t, ma, mb) = (POOL[64], POOL[65], POOL[66]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[0];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[67];
    r[1] = r[3] ^ r[9];
    r[0] = r[2] ^ r[1];
    r[1] = r[4] & POOL[68];
    r[2] = {
        let (t, ma, mb) = (POOL[69], POOL[70], POOL[71]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[2];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[72];
    r[1] = r[3] ^ r[9];
    r[2] = r[0] ^ r[1];
    r[1] = r[4] & POOL[73];
    r[0] = {
        let (t, ma, mb) = (POOL[74], POOL[75], POOL[76]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[0];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[77];
    r[1] = r[3] ^ r[9];
    r[0] = r[2] ^ r[1];
    r[1] = r[4] & POOL[78];
    r[2] = {
        let (t, ma, mb) = (POOL[79], POOL[80], POOL[81]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[2];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[82];
    r[1] = r[3] ^ r[9];
    r[2] = r[0] ^ r[1];
    r[1] = r[4] & POOL[83];
    r[0] = {
        let (t, ma, mb) = (POOL[84], POOL[85], POOL[86]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[0];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[87];
    r[1] = r[3] ^ r[9];
    r[0] = r[2] ^ r[1];
    r[1] = r[4] & POOL[88];
    r[2] = {
        let (t, ma, mb) = (POOL[89], POOL[90], POOL[91]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[2];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[92];
    r[1] = r[3] ^ r[9];
    r[2] = r[0] ^ r[1];
    r[1] = r[4] & POOL[93];
    r[0] = {
        let (t, ma, mb) = (POOL[94], POOL[95], POOL[96]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[0];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[97];
    r[1] = r[3] ^ r[9];
    r[0] = r[2] ^ r[1];
    r[1] = r[4] & POOL[98];
    r[2] = {
        let (t, ma, mb) = (POOL[99], POOL[100], POOL[101]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[2];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[102];
    r[1] = r[3] ^ r[9];
    r[2] = r[0] ^ r[1];
    r[1] = r[4] & POOL[103];
    r[0] = {
        let (t, ma, mb) = (POOL[104], POOL[105], POOL[106]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[0];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[107];
    r[1] = r[3] ^ r[9];
    r[0] = r[2] ^ r[1];
    r[1] = r[4] & POOL[108];
    r[2] = {
        let (t, ma, mb) = (POOL[109], POOL[110], POOL[111]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[2];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[112];
    r[1] = r[3] ^ r[9];
    r[2] = r[0] ^ r[1];
    r[1] = r[4] & POOL[113];
    r[0] = {
        let (t, ma, mb) = (POOL[114], POOL[115], POOL[116]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[0];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[117];
    r[1] = r[3] ^ r[9];
    r[0] = r[2] ^ r[1];
    r[1] = r[4] & POOL[118];
    r[2] = {
        let (t, ma, mb) = (POOL[119], POOL[120], POOL[121]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[2];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[122];
    r[1] = r[3] ^ r[9];
    r[2] = r[0] ^ r[1];
    r[1] = r[4] & POOL[123];
    r[0] = {
        let (t, ma, mb) = (POOL[124], POOL[125], POOL[126]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[0];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[127];
    r[1] = r[3] ^ r[9];
    r[0] = r[2] ^ r[1];
    r[1] = r[4] & POOL[128];
    r[2] = {
        let (t, ma, mb) = (POOL[129], POOL[130], POOL[131]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[2];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[132];
    r[1] = r[3] ^ r[9];
    r[2] = r[0] ^ r[1];
    r[1] = r[4] & POOL[133];
    r[0] = {
        let (t, ma, mb) = (POOL[134], POOL[135], POOL[136]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[0];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[137];
    r[1] = r[3] ^ r[9];
    r[0] = r[2] ^ r[1];
    r[1] = r[4] & POOL[138];
    r[2] = {
        let (t, ma, mb) = (POOL[139], POOL[140], POOL[141]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[2];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[142];
    r[1] = r[3] ^ r[9];
    r[2] = r[0] ^ r[1];
    r[1] = r[4] & POOL[143];
    r[0] = {
        let (t, ma, mb) = (POOL[144], POOL[145], POOL[146]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[0];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[147];
    r[1] = r[3] ^ r[9];
    r[0] = r[2] ^ r[1];
    r[1] = r[4] & POOL[148];
    r[2] = {
        let (t, ma, mb) = (POOL[149], POOL[150], POOL[151]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[2];
    r[9] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[152];
    r[1] = r[3] ^ r[9];
    r[2] = r[0] ^ r[1];
    r[1] = r[4] & POOL[153];
    r[4] = {
        let (t, ma, mb) = (POOL[154], POOL[155], POOL[156]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[9] & ma;
        z ^= r[3] & r[9];
        z
    };
    r[3] = r[1] ^ r[4];
    r[4] = r[3].rotate_left(1);
    r[3] = r[6] & POOL[157];
    r[6] = r[3] ^ r[4];
    r[3] = r[2] ^ r[6];
    r[4] = c ^ POOL[158];
    r[6] = d ^ POOL[159];
    r[9] = r[6] ^ r[3];
    r[6] = r[9].rotate_left(16);
    r[9] = {
        let (t, ma, mb) = (POOL[160], POOL[161], POOL[162]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[6] & ma;
        z ^= r[4] & r[6];
        z
    };
    r[1] = r[4] ^ r[6];
    r[4] = r[1] & POOL[163];
    r[2] = r[9] & POOL[164];
    r[0] = r[2].rotate_left(1);
    r[2] = r[1] & POOL[165];
    r[7] = r[2] ^ r[0];
    r[8] = r[4] ^ r[7];
    r[4] = r[9] & POOL[166];
    r[7] = {
        let (t, ma, mb) = (POOL[167], POOL[168], POOL[169]);
        let mut z = t;
        z ^= r[2] & mb;
        z ^= r[0] & ma;
        z ^= r[2] & r[0];
        z
    };
    r[2] = r[4] ^ r[7];
    r[4] = r[2].rotate_left(1);
    r[2] = r[1] & POOL[170];
    r[0] = r[2] ^ r[4];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[171];
    r[8] = {
        let (t, ma, mb) = (POOL[172], POOL[173], POOL[174]);
        let mut z = t;
        z ^= r[2] & mb;
        z ^= r[4] & ma;
        z ^= r[2] & r[4];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[175];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[176];
    r[7] = {
        let (t, ma, mb) = (POOL[177], POOL[178], POOL[179]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[180];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[181];
    r[8] = {
        let (t, ma, mb) = (POOL[182], POOL[183], POOL[184]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[185];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[186];
    r[7] = {
        let (t, ma, mb) = (POOL[187], POOL[188], POOL[189]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[190];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[191];
    r[8] = {
        let (t, ma, mb) = (POOL[192], POOL[193], POOL[194]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[195];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[196];
    r[7] = {
        let (t, ma, mb) = (POOL[197], POOL[198], POOL[199]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[200];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[201];
    r[8] = {
        let (t, ma, mb) = (POOL[202], POOL[203], POOL[204]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[205];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[206];
    r[7] = {
        let (t, ma, mb) = (POOL[207], POOL[208], POOL[209]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[210];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[211];
    r[8] = {
        let (t, ma, mb) = (POOL[212], POOL[213], POOL[214]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[215];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[216];
    r[7] = {
        let (t, ma, mb) = (POOL[217], POOL[218], POOL[219]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[220];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[221];
    r[8] = {
        let (t, ma, mb) = (POOL[222], POOL[223], POOL[224]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[225];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[226];
    r[7] = {
        let (t, ma, mb) = (POOL[227], POOL[228], POOL[229]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[230];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[231];
    r[8] = {
        let (t, ma, mb) = (POOL[232], POOL[233], POOL[234]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[235];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[236];
    r[7] = {
        let (t, ma, mb) = (POOL[237], POOL[238], POOL[239]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[240];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[241];
    r[8] = {
        let (t, ma, mb) = (POOL[242], POOL[243], POOL[244]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[245];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[246];
    r[7] = {
        let (t, ma, mb) = (POOL[247], POOL[248], POOL[249]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[250];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[251];
    r[8] = {
        let (t, ma, mb) = (POOL[252], POOL[253], POOL[254]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[255];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[256];
    r[7] = {
        let (t, ma, mb) = (POOL[257], POOL[258], POOL[259]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[260];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[261];
    r[8] = {
        let (t, ma, mb) = (POOL[262], POOL[263], POOL[264]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[265];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[266];
    r[7] = {
        let (t, ma, mb) = (POOL[267], POOL[268], POOL[269]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[270];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[271];
    r[8] = {
        let (t, ma, mb) = (POOL[272], POOL[273], POOL[274]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[275];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[276];
    r[7] = {
        let (t, ma, mb) = (POOL[277], POOL[278], POOL[279]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[280];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[281];
    r[8] = {
        let (t, ma, mb) = (POOL[282], POOL[283], POOL[284]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[285];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[286];
    r[7] = {
        let (t, ma, mb) = (POOL[287], POOL[288], POOL[289]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[290];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[291];
    r[8] = {
        let (t, ma, mb) = (POOL[292], POOL[293], POOL[294]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[295];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[296];
    r[7] = {
        let (t, ma, mb) = (POOL[297], POOL[298], POOL[299]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[300];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[301];
    r[8] = {
        let (t, ma, mb) = (POOL[302], POOL[303], POOL[304]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[305];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[306];
    r[7] = {
        let (t, ma, mb) = (POOL[307], POOL[308], POOL[309]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[310];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[311];
    r[9] = {
        let (t, ma, mb) = (POOL[312], POOL[313], POOL[314]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[9];
    r[9] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[315];
    r[1] = r[4] ^ r[9];
    r[4] = r[7] ^ r[1];
    r[9] = r[5] ^ r[4];
    r[5] = r[9].rotate_left(12);
    r[9] = {
        let (t, ma, mb) = (POOL[316], POOL[317], POOL[318]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[5] & ma;
        z ^= r[3] & r[5];
        z
    };
    r[1] = r[3] ^ r[5];
    r[3] = r[1] & POOL[319];
    r[2] = r[9] & POOL[320];
    r[0] = r[2].rotate_left(1);
    r[2] = r[1] & POOL[321];
    r[7] = r[2] ^ r[0];
    r[8] = r[3] ^ r[7];
    r[3] = r[9] & POOL[322];
    r[7] = {
        let (t, ma, mb) = (POOL[323], POOL[324], POOL[325]);
        let mut z = t;
        z ^= r[2] & mb;
        z ^= r[0] & ma;
        z ^= r[2] & r[0];
        z
    };
    r[2] = r[3] ^ r[7];
    r[3] = r[2].rotate_left(1);
    r[2] = r[1] & POOL[326];
    r[0] = r[2] ^ r[3];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[327];
    r[8] = {
        let (t, ma, mb) = (POOL[328], POOL[329], POOL[330]);
        let mut z = t;
        z ^= r[2] & mb;
        z ^= r[3] & ma;
        z ^= r[2] & r[3];
        z
    };
    r[3] = r[0] ^ r[8];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[331];
    r[0] = r[3] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[332];
    r[7] = {
        let (t, ma, mb) = (POOL[333], POOL[334], POOL[335]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[7];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[336];
    r[0] = r[3] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[337];
    r[8] = {
        let (t, ma, mb) = (POOL[338], POOL[339], POOL[340]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[8];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[341];
    r[0] = r[3] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[342];
    r[7] = {
        let (t, ma, mb) = (POOL[343], POOL[344], POOL[345]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[7];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[346];
    r[0] = r[3] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[347];
    r[8] = {
        let (t, ma, mb) = (POOL[348], POOL[349], POOL[350]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[8];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[351];
    r[0] = r[3] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[352];
    r[7] = {
        let (t, ma, mb) = (POOL[353], POOL[354], POOL[355]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[7];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[356];
    r[0] = r[3] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[357];
    r[8] = {
        let (t, ma, mb) = (POOL[358], POOL[359], POOL[360]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[8];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[361];
    r[0] = r[3] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[362];
    r[7] = {
        let (t, ma, mb) = (POOL[363], POOL[364], POOL[365]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[7];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[366];
    r[0] = r[3] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[367];
    r[8] = {
        let (t, ma, mb) = (POOL[368], POOL[369], POOL[370]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[8];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[371];
    r[0] = r[3] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[372];
    r[7] = {
        let (t, ma, mb) = (POOL[373], POOL[374], POOL[375]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[7];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[376];
    r[0] = r[3] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[377];
    r[8] = {
        let (t, ma, mb) = (POOL[378], POOL[379], POOL[380]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[8];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[381];
    r[0] = r[3] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[382];
    r[7] = {
        let (t, ma, mb) = (POOL[383], POOL[384], POOL[385]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[7];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[386];
    r[0] = r[3] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[387];
    r[8] = {
        let (t, ma, mb) = (POOL[388], POOL[389], POOL[390]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[8];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[391];
    r[0] = r[3] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[392];
    r[7] = {
        let (t, ma, mb) = (POOL[393], POOL[394], POOL[395]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[7];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[396];
    r[0] = r[3] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[397];
    r[8] = {
        let (t, ma, mb) = (POOL[398], POOL[399], POOL[400]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[8];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[401];
    r[0] = r[3] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[402];
    r[7] = {
        let (t, ma, mb) = (POOL[403], POOL[404], POOL[405]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[7];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[406];
    r[0] = r[3] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[407];
    r[8] = {
        let (t, ma, mb) = (POOL[408], POOL[409], POOL[410]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[8];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[411];
    r[0] = r[3] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[412];
    r[7] = {
        let (t, ma, mb) = (POOL[413], POOL[414], POOL[415]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[7];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[416];
    r[0] = r[3] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[417];
    r[8] = {
        let (t, ma, mb) = (POOL[418], POOL[419], POOL[420]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[8];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[421];
    r[0] = r[3] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[422];
    r[7] = {
        let (t, ma, mb) = (POOL[423], POOL[424], POOL[425]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[7];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[426];
    r[0] = r[3] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[427];
    r[8] = {
        let (t, ma, mb) = (POOL[428], POOL[429], POOL[430]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[8];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[431];
    r[0] = r[3] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[432];
    r[7] = {
        let (t, ma, mb) = (POOL[433], POOL[434], POOL[435]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[7];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[436];
    r[0] = r[3] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[437];
    r[8] = {
        let (t, ma, mb) = (POOL[438], POOL[439], POOL[440]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[8];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[441];
    r[0] = r[3] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[442];
    r[7] = {
        let (t, ma, mb) = (POOL[443], POOL[444], POOL[445]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[7];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[446];
    r[0] = r[3] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[447];
    r[8] = {
        let (t, ma, mb) = (POOL[448], POOL[449], POOL[450]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[8];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[451];
    r[0] = r[3] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[452];
    r[7] = {
        let (t, ma, mb) = (POOL[453], POOL[454], POOL[455]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[7];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[456];
    r[0] = r[3] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[457];
    r[8] = {
        let (t, ma, mb) = (POOL[458], POOL[459], POOL[460]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[8];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[461];
    r[0] = r[3] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[462];
    r[7] = {
        let (t, ma, mb) = (POOL[463], POOL[464], POOL[465]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[7];
    r[2] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[466];
    r[0] = r[3] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[467];
    r[9] = {
        let (t, ma, mb) = (POOL[468], POOL[469], POOL[470]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[0] ^ r[9];
    r[9] = r[3].rotate_left(1);
    r[3] = r[1] & POOL[471];
    r[1] = r[3] ^ r[9];
    r[3] = r[7] ^ r[1];
    r[9] = r[6] ^ r[3];
    r[6] = r[9].rotate_left(8);
    r[9] = {
        let (t, ma, mb) = (POOL[472], POOL[473], POOL[474]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[6] & ma;
        z ^= r[4] & r[6];
        z
    };
    r[1] = r[4] ^ r[6];
    r[4] = r[1] & POOL[475];
    r[2] = r[9] & POOL[476];
    r[0] = r[2].rotate_left(1);
    r[2] = r[1] & POOL[477];
    r[7] = r[2] ^ r[0];
    r[8] = r[4] ^ r[7];
    r[4] = r[9] & POOL[478];
    r[7] = {
        let (t, ma, mb) = (POOL[479], POOL[480], POOL[481]);
        let mut z = t;
        z ^= r[2] & mb;
        z ^= r[0] & ma;
        z ^= r[2] & r[0];
        z
    };
    r[2] = r[4] ^ r[7];
    r[4] = r[2].rotate_left(1);
    r[2] = r[1] & POOL[482];
    r[0] = r[2] ^ r[4];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[483];
    r[8] = {
        let (t, ma, mb) = (POOL[484], POOL[485], POOL[486]);
        let mut z = t;
        z ^= r[2] & mb;
        z ^= r[4] & ma;
        z ^= r[2] & r[4];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[487];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[488];
    r[7] = {
        let (t, ma, mb) = (POOL[489], POOL[490], POOL[491]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[492];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[493];
    r[8] = {
        let (t, ma, mb) = (POOL[494], POOL[495], POOL[496]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[497];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[498];
    r[7] = {
        let (t, ma, mb) = (POOL[499], POOL[500], POOL[501]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[502];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[503];
    r[8] = {
        let (t, ma, mb) = (POOL[504], POOL[505], POOL[506]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[507];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[508];
    r[7] = {
        let (t, ma, mb) = (POOL[509], POOL[510], POOL[511]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[512];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[513];
    r[8] = {
        let (t, ma, mb) = (POOL[514], POOL[515], POOL[516]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[517];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[518];
    r[7] = {
        let (t, ma, mb) = (POOL[519], POOL[520], POOL[521]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[522];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[523];
    r[8] = {
        let (t, ma, mb) = (POOL[524], POOL[525], POOL[526]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[527];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[528];
    r[7] = {
        let (t, ma, mb) = (POOL[529], POOL[530], POOL[531]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[532];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[533];
    r[8] = {
        let (t, ma, mb) = (POOL[534], POOL[535], POOL[536]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[537];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[538];
    r[7] = {
        let (t, ma, mb) = (POOL[539], POOL[540], POOL[541]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[542];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[543];
    r[8] = {
        let (t, ma, mb) = (POOL[544], POOL[545], POOL[546]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[547];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[548];
    r[7] = {
        let (t, ma, mb) = (POOL[549], POOL[550], POOL[551]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[552];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[553];
    r[8] = {
        let (t, ma, mb) = (POOL[554], POOL[555], POOL[556]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[557];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[558];
    r[7] = {
        let (t, ma, mb) = (POOL[559], POOL[560], POOL[561]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[562];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[563];
    r[8] = {
        let (t, ma, mb) = (POOL[564], POOL[565], POOL[566]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[567];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[568];
    r[7] = {
        let (t, ma, mb) = (POOL[569], POOL[570], POOL[571]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[572];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[573];
    r[8] = {
        let (t, ma, mb) = (POOL[574], POOL[575], POOL[576]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[577];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[578];
    r[7] = {
        let (t, ma, mb) = (POOL[579], POOL[580], POOL[581]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[582];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[583];
    r[8] = {
        let (t, ma, mb) = (POOL[584], POOL[585], POOL[586]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[587];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[588];
    r[7] = {
        let (t, ma, mb) = (POOL[589], POOL[590], POOL[591]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[592];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[593];
    r[8] = {
        let (t, ma, mb) = (POOL[594], POOL[595], POOL[596]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[597];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[598];
    r[7] = {
        let (t, ma, mb) = (POOL[599], POOL[600], POOL[601]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[602];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[603];
    r[8] = {
        let (t, ma, mb) = (POOL[604], POOL[605], POOL[606]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[607];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[608];
    r[7] = {
        let (t, ma, mb) = (POOL[609], POOL[610], POOL[611]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[612];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[613];
    r[8] = {
        let (t, ma, mb) = (POOL[614], POOL[615], POOL[616]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[8];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[617];
    r[0] = r[4] ^ r[2];
    r[8] = r[7] ^ r[0];
    r[0] = r[9] & POOL[618];
    r[7] = {
        let (t, ma, mb) = (POOL[619], POOL[620], POOL[621]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[7];
    r[2] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[622];
    r[0] = r[4] ^ r[2];
    r[7] = r[8] ^ r[0];
    r[0] = r[9] & POOL[623];
    r[9] = {
        let (t, ma, mb) = (POOL[624], POOL[625], POOL[626]);
        let mut z = t;
        z ^= r[4] & mb;
        z ^= r[2] & ma;
        z ^= r[4] & r[2];
        z
    };
    r[4] = r[0] ^ r[9];
    r[9] = r[4].rotate_left(1);
    r[4] = r[1] & POOL[627];
    r[1] = r[4] ^ r[9];
    r[4] = r[7] ^ r[1];
    r[9] = r[5] ^ r[4];
    r[5] = r[9].rotate_left(7);
    r[9] = r[3] ^ r[5];
    r[3] = r[4] ^ r[6];
    r[5] = r[9] ^ r[3];
    r[5] ^ POOL[628]
}
