// Generated by xorpl — do not edit manually.
pub const ROTATION_TAG: u32 = 0x7b0e5d25;
pub fn mux_demo_verify(input_cond: u32, input_t: u32, input_f: u32) -> u32 {
    let w0 = input_cond;
    let w1 = input_t;
    let w2 = input_f;
    let w3 = w1 ^ w2;
    let w4 = w0 & w3;
    let w5 = w2 ^ w4;
    w5
}
