// Generated by `cargo run --bin regen_fixtures` — do not edit manually.
pub const ROTATION_TAG: u32 = 0x7b0e5d25;
pub fn mux_demo(cond: u32, t: u32, f: u32) -> u32 {
    const POOL: &[u32] = &[
        0xcd2c6f7f,
        0xbb2a3fb2,
        0x8e27697b,
        0xc30d3add,
        0xcd2c6f7f,
        0x350d56c9,
        0x482615ef,
    ];
    let mut r = [0u32; 4];
    r[3] = cond ^ POOL[0];
    r[0] = t ^ POOL[1];
    r[1] = f ^ POOL[2];
    r[2] = r[0] ^ r[1];
    r[0] = {
        let (t, ma, mb) = (POOL[3], POOL[4], POOL[5]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[1] ^ r[0];
    r[3] ^ POOL[6]
}
