// Generated by `cargo run --bin regen_fixtures` — do not edit manually.
pub const EXPR_DIGEST: [u8; 32] = [
    0x0d, 0x94, 0x50, 0x8d, 0x20, 0x3a, 0x11, 0x1a,
    0x10, 0x20, 0xdd, 0xea, 0x2c, 0x85, 0x04, 0x60,
    0x50, 0x05, 0x36, 0x60, 0x9a, 0xe0, 0xa4, 0x42,
    0x10, 0x7c, 0xda, 0x3e, 0x4e, 0x9c, 0xd6, 0x1b,
];
pub fn mux_demo(cond: u32, t: u32, f: u32) -> u32 {
    const POOL: &[u32] = &[
        0xcd2c6f7f,
        0xbb2a3fb2,
        0x8e27697b,
        0xc30d3add,
        0xcd2c6f7f,
        0x350d56c9,
        0x482615ef,
    ];
    let mut r = [0u32; 4];
    r[3] = cond ^ POOL[0];
    r[0] = t ^ POOL[1];
    r[1] = f ^ POOL[2];
    r[2] = r[0] ^ r[1];
    r[0] = {
        let (t, ma, mb) = (POOL[3], POOL[4], POOL[5]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[2] & ma;
        z ^= r[3] & r[2];
        z
    };
    r[3] = r[1] ^ r[0];
    r[3] ^ POOL[6]
}
