// Generated by `cargo run --bin regen_fixtures` — do not edit manually.
pub fn mux_demo(cond: u32, t: u32, f: u32) -> u32 {
    const POOL: &[u32] = &[
        0x8e27697b,
        0xc6017c94,
        0xcf310a16,
        0x0ebda100,
        0x8e27697b,
        0x09307682,
        0xc9accb14,
    ];
    let mut r = [0u32; 4];
    r[0] = cond ^ POOL[0];
    r[3] = t ^ POOL[1];
    r[1] = f ^ POOL[2];
    r[2] = r[3] ^ r[1];
    r[3] = {
        let (t, ma, mb) = (POOL[3], POOL[4], POOL[5]);
        let mut z = t;
        z ^= r[0] & mb;
        z ^= r[2] & ma;
        z ^= r[0] & r[2];
        z
    };
    r[0] = r[1] ^ r[3];
    r[0] ^ POOL[6]
}
