// Generated by xorpl — do not edit manually.
pub const ROTATION_TAG: u32 = 0x332eada8;
pub fn or_rotl_demo_verify(a: u32, b: u32) -> u32 {
    let w0 = a;
    let w1 = b;
    let w2 = w0 ^ w1;
    let w3 = w0 & w1;
    let w4 = w2 ^ w3;
    let w5 = 0x9e3779b9u32;
    let w6 = w4 ^ w5;
    let w7 = w6.rotate_left(5);
    w7
}
