// Generated by `cargo run --bin regen_fixtures` — do not edit manually.
pub const EXPR_DIGEST: [u8; 32] = [
    0xe1, 0x43, 0xce, 0xb2, 0x2a, 0xa9, 0xa2, 0xae,
    0x3a, 0x84, 0x4f, 0x61, 0x9b, 0x1d, 0xf2, 0x5f,
    0x09, 0xfc, 0xb2, 0x56, 0xeb, 0x39, 0xf5, 0xe4,
    0xc6, 0x2e, 0x19, 0xcf, 0xaf, 0xd9, 0x44, 0x40,
];
pub fn or_rotl_mux_decoy(a: u32, b: u32) -> u32 {
    const POOL: &[u32] = &[
        0x32d39080,
        0xbb2a3fb2,
        0x8e27697b,
        0x4c2355a6,
        0xbb2a3fb2,
        0x8e27697b,
        0x510673af,
        0x8cbfe830,
        0xbb2a3fb2,
        0x8e27697b,
        0x2acdbeb5,
        0xcd2c6f7f,
        0x8139c865,
        0xad7837d2,
    ];
    let mut r = [0u32; 6];
    r[3] = POOL[0];
    r[1] = a ^ POOL[1];
    r[5] = b ^ POOL[2];
    r[0] = r[1] ^ r[5];
    r[4] = {
        let (t, ma, mb) = (POOL[3], POOL[4], POOL[5]);
        let mut z = t;
        z ^= r[1] & mb;
        z ^= r[5] & ma;
        z ^= r[1] & r[5];
        z
    };
    r[2] = r[0] ^ r[4];
    r[0] = POOL[6];
    r[4] = r[2] ^ r[0];
    r[0] = r[4].rotate_left(5);
    r[4] = {
        let (t, ma, mb) = (POOL[7], POOL[8], POOL[9]);
        let mut z = t;
        z ^= r[1] & mb;
        z ^= r[5] & ma;
        z ^= r[1] & r[5];
        z
    };
    r[1] = r[0] ^ r[4];
    r[5] = {
        let (t, ma, mb) = (POOL[10], POOL[11], POOL[12]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[1] & ma;
        z ^= r[3] & r[1];
        z
    };
    r[3] = r[4] ^ r[5];
    r[3] ^ POOL[13]
}
