// Generated by `cargo run --bin regen_fixtures` — do not edit manually.
pub fn or_rotl_mux_decoy(a: u32, b: u32) -> u32 {
    const POOL: &[u32] = &[
        0x71d89684,
        0xc6017c94,
        0xcf310a16,
        0xc09cc916,
        0xc6017c94,
        0xcf310a16,
        0x35d28f69,
        0x538a7e09,
        0xc6017c94,
        0xcf310a16,
        0xd2e23318,
        0x8e27697b,
        0x1c835c09,
        0x4b6a0d0c,
    ];
    let mut r = [0u32; 6];
    r[5] = POOL[0];
    r[3] = a ^ POOL[1];
    r[1] = b ^ POOL[2];
    r[2] = r[3] ^ r[1];
    r[0] = {
        let (t, ma, mb) = (POOL[3], POOL[4], POOL[5]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[1] & ma;
        z ^= r[3] & r[1];
        z
    };
    r[4] = r[2] ^ r[0];
    r[2] = POOL[6];
    r[0] = r[4] ^ r[2];
    r[2] = r[0].rotate_left(5);
    r[0] = {
        let (t, ma, mb) = (POOL[7], POOL[8], POOL[9]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[1] & ma;
        z ^= r[3] & r[1];
        z
    };
    r[3] = r[2] ^ r[0];
    r[1] = {
        let (t, ma, mb) = (POOL[10], POOL[11], POOL[12]);
        let mut z = t;
        z ^= r[5] & mb;
        z ^= r[3] & ma;
        z ^= r[5] & r[3];
        z
    };
    r[5] = r[0] ^ r[1];
    r[5] ^ POOL[13]
}
