// Generated by `cargo run --bin regen_fixtures` — do not edit manually.
pub fn or_rotl_demo(a: u32, b: u32) -> u32 {
    const POOL: &[u32] = &[
        0x8e27697b,
        0xc6017c94,
        0x49306206,
        0x8e27697b,
        0xc6017c94,
        0x98aab8bb,
        0x315bdf70,
    ];
    let mut r = [0u32; 4];
    r[0] = a ^ POOL[0];
    r[3] = b ^ POOL[1];
    r[1] = r[0] ^ r[3];
    r[2] = {
        let (t, ma, mb) = (POOL[2], POOL[3], POOL[4]);
        let mut z = t;
        z ^= r[0] & mb;
        z ^= r[3] & ma;
        z ^= r[0] & r[3];
        z
    };
    r[0] = r[1] ^ r[2];
    r[3] = POOL[5];
    r[1] = r[0] ^ r[3];
    r[0] = r[1].rotate_left(5);
    r[0] ^ POOL[6]
}
