// Generated by xorpl — do not edit manually.
pub const EXPR_DIGEST: [u8; 32] = [
    0xe1, 0x43, 0xce, 0xb2, 0x2a, 0xa9, 0xa2, 0xae,
    0x3a, 0x84, 0x4f, 0x61, 0x9b, 0x1d, 0xf2, 0x5f,
    0x09, 0xfc, 0xb2, 0x56, 0xeb, 0x39, 0xf5, 0xe4,
    0xc6, 0x2e, 0x19, 0xcf, 0xaf, 0xd9, 0x44, 0x40,
];
pub fn or_rotl_mux_decoy_verify(input_a: u32, input_b: u32) -> u32 {
    let w0 = 0xffffffffu32;
    let w1 = input_a;
    let w2 = input_b;
    let w3 = w1 ^ w2;
    let w4 = w1 & w2;
    let w5 = w3 ^ w4;
    let w6 = 0x9e3779b9u32;
    let w7 = w5 ^ w6;
    let w8 = w7.rotate_left(5);
    let w9 = w1 & w2;
    let w10 = w8 ^ w9;
    let w11 = w0 & w10;
    let w12 = w9 ^ w11;
    w12
}
