// Generated by `cargo run --bin regen_fixtures` — do not edit manually.
pub const EXPR_DIGEST: [u8; 32] = [
    0x2c, 0x78, 0x66, 0x85, 0x7a, 0xce, 0x2e, 0x6a,
    0x4f, 0xc4, 0xbf, 0xf6, 0x51, 0xa1, 0x56, 0xb7,
    0x9c, 0x7c, 0x30, 0xe0, 0x28, 0x84, 0xd1, 0x40,
    0x42, 0xb1, 0xca, 0x93, 0xc4, 0xcd, 0x72, 0x37,
];
pub fn or_rotl_demo(a: u32, b: u32) -> u32 {
    const POOL: &[u32] = &[
        0xcd2c6f7f,
        0xbb2a3fb2,
        0x070f4649,
        0xcd2c6f7f,
        0xbb2a3fb2,
        0x5836052d,
        0xc408a447,
    ];
    let mut r = [0u32; 4];
    r[3] = a ^ POOL[0];
    r[0] = b ^ POOL[1];
    r[1] = r[3] ^ r[0];
    r[2] = {
        let (t, ma, mb) = (POOL[2], POOL[3], POOL[4]);
        let mut z = t;
        z ^= r[3] & mb;
        z ^= r[0] & ma;
        z ^= r[3] & r[0];
        z
    };
    r[3] = r[1] ^ r[2];
    r[0] = POOL[5];
    r[1] = r[3] ^ r[0];
    r[3] = r[1].rotate_left(5);
    r[3] ^ POOL[6]
}
