// Generated by `cargo run --bin regen_fixtures` — do not edit manually.
pub fn or_rotl_demo(a: u32, b: u32) -> u32 {
    const POOL: &[u32] = &[
        0xcd2c6f7f,
        0xbb2a3fb2,
        0x070f4649,
        0xcd2c6f7f,
        0xbb2a3fb2,
        0x5836052d,
        0xc408a447,
    ];
    let mut r = [0u32; 8];
    r[0] = a ^ POOL[0];
    r[1] = b ^ POOL[1];
    r[2] = r[0] ^ r[1];
    r[3] = {
        let (t, ma, mb) = (POOL[2], POOL[3], POOL[4]);
        let mut z = t;
        z ^= r[0] & mb;
        z ^= r[1] & ma;
        z ^= r[0] & r[1];
        z
    };
    r[4] = r[2] ^ r[3];
    r[5] = POOL[5];
    r[6] = r[4] ^ r[5];
    r[7] = r[6].rotate_left(5);
    r[7] ^ POOL[6]
}
