// Generated by xorpl — do not edit manually.
pub const ROTATION_TAG: u32 = 0xa586a3c6;
pub fn or_rotl_mux_decoy_verify(input_a: u32, input_b: u32) -> u32 {
    let w0 = 0xffffffffu32;
    let w1 = input_a;
    let w2 = input_b;
    let w3 = w1 ^ w2;
    let w4 = w1 & w2;
    let w5 = w3 ^ w4;
    let w6 = 0x9e3779b9u32;
    let w7 = w5 ^ w6;
    let w8 = w7.rotate_left(5);
    let w9 = w1 & w2;
    let w10 = w8 ^ w9;
    let w11 = w0 & w10;
    let w12 = w9 ^ w11;
    w12
}
