//! Emission: `ConcreteVm` → Rust source code.
//!
//! This module takes a baked, concrete VM and emits a standalone Rust function
//! that implements the same computation without any VM machinery — just array
//! accesses, XOR, AND, and rotation on `u32` values.
//!
//! The emitted function is what gets shipped to the client (compiled to Wasm
//! or included in a JS bundle). A new rotation means re-running
//! `ConcreteVm::from_circuit` with a new seed and re-emitting; the circuit
//! structure stays the same, only the constants change.
//!
//! # Emitted shape
//!
//! ```rust,ignore
//! pub fn checksum(a: u32, b: u32) -> u32 {
//!     const POOL: &[u32] = &[0xdeadbeef, 0xcafebabe, /* ... */];
//!     let mut r = [0u32; N];           // N = number of non-egress wires
//!
//!     // One block per gadget, in topological order:
//!
//!     r[0] = a ^ POOL[0];              // INGEST "a"
//!     r[1] = b ^ POOL[1];              // INGEST "b"
//!     r[2] = POOL[2];                  // SECRET_CONST  (k^mask baked in)
//!     r[3] = r[0] ^ r[1];             // XOR  (free)
//!     r[4] = {                         // AND  (Beaver triple expansion)
//!         let (t, ma, mb) = (POOL[3], POOL[4], POOL[5]);
//!         let mut z = t;
//!         z ^= r[0] & mb;
//!         z ^= r[1] & ma;
//!         z ^= r[0] & r[1];
//!         z
//!     };
//!     // ...
//!     r[K] ^ POOL[M]                   // EGRESS: XOR with unmask delta
//! }
//! ```
//!
//! # Register allocation
//!
//! `allocate_registers` runs a linear scan over the gadget schedule:
//!
//! 1. One forward pass computes each wire's last-use step.
//! 2. A second pass assigns the lowest available slot to each output wire and
//!    schedules slot reclamation the step after the wire's last read.
//! 3. The compact slot mapping (`WireId → slot`) is then randomly permuted
//!    with an RNG seeded from `ConcreteVm::emit_seed`, so the `r[k]` indices
//!    in the emitted code vary across rotations without affecting semantics.
//!
//! For the ChaCha QR the naive 1:1 mapping required ~880 slots; live-range
//! allocation reduces this to ~40 (the actual live-wire peak of the circuit).
//!
//! # Constant pool layout
//!
//! Constants are emitted in gadget order, concatenated into a single `POOL`
//! slice. Each gadget records how many pool entries it owns (already tracked
//! in `BakedGadget::consts`), so indexing is straightforward.
//!
//! # Future: structured output
//!
//! The current design returns a `String`. If the emission target changes (e.g.
//! emitting JavaScript or Wasm bytecode directly), this function's signature
//! should change to return a `proc_macro2::TokenStream` or a target-specific
//! IR, keeping the gadget-walking logic intact.

use crate::circuit::{Circuit, Gadget, WireId};
use crate::mask::MaskedCircuit;

fn format_digest_const(digest: &[u8; 32]) -> String {
    let mut s = String::from("pub const EXPR_DIGEST: [u8; 32] = [\n");
    for row in digest.chunks(8) {
        s.push_str("    ");
        s.push_str(&row.iter().map(|b| format!("0x{b:02x}")).collect::<Vec<_>>().join(", "));
        s.push_str(",\n");
    }
    s.push_str("];\n");
    s
}

// ---------------------------------------------------------------------------
// Browser Wasm entry point
// ---------------------------------------------------------------------------

/// Emit a self-contained Rust source file containing a single function for
/// the given concrete VM.
///
/// `fn_name` — the name of the emitted function (also the file stem).
///
/// The function's parameter list is derived directly from the circuit's
/// `Gadget::Ingest` entries in topological order — each ingest's `name`
/// field becomes a `u32` parameter.  The caller must ensure those names are
/// valid Rust identifiers.
///
/// Returns a `String` containing a complete Rust source file that can be
/// written to disk and compiled independently of this crate.
pub fn emit_rust(masked: &MaskedCircuit, circuit: &Circuit, fn_name: &str, rng: &mut impl rand::RngCore, expr_digest: &[u8; 32]) -> String {
    let slot = allocate_registers(circuit, rng);

    let (pool, pool_starts) = build_pool(masked);

    let n_regs = circuit.gadgets.iter()
        .filter_map(|g| g.out())
        .map(|w| slot[w])
        .max()
        .map(|m| m + 1)
        .unwrap_or(0);

    let sig_params = circuit.gadgets.iter()
        .filter_map(|g| if let Gadget::Ingest { name, .. } = g { Some(name.as_str()) } else { None })
        .map(|name| format!("{name}: u32"))
        .collect::<Vec<_>>()
        .join(", ");

    let mut out = String::new();

    out.push_str("// Generated by `cargo run --bin regen_fixtures` — do not edit manually.\n");
    out.push_str(&format_digest_const(expr_digest));
    out.push_str(&format!("pub fn {fn_name}({sig_params}) -> u32 {{\n"));

    out.push_str("    const POOL: &[u32] = &[\n");
    for &v in &pool {
        out.push_str(&format!("        0x{v:08x},\n"));
    }
    out.push_str("    ];\n");

    out.push_str(&format!("    let mut r = [0u32; {n_regs}];\n"));

    for (idx, g) in circuit.gadgets.iter().enumerate() {
        out.push_str(&emit_gadget(g, pool_starts[idx], &slot));
    }

    out.push_str("}\n");
    out
}

// ---------------------------------------------------------------------------
// Server verifier entry point
// ---------------------------------------------------------------------------

/// Emit a self-contained, unmasked Rust evaluation function for server-side
/// verification.
///
/// The emitted function evaluates F(inputs) plaintext — no POOL, no Beaver
/// triples, no masking.  It is the server's oracle: given the same inputs as
/// the browser, it must produce the same `u32` checksum.
///
/// Intended use: write the output to `generated/verifier.rs` inside a
/// `workers-rs` Cloudflare Worker crate, then `include!` it.  The crate has
/// no dependency on xorpl at runtime.
///
/// Each Remask gadget emits a transparent identity assignment (`let wN = wM`)
/// which the compiler eliminates.  All other gadgets map directly to their
/// unmasked arithmetic.
///
/// Parameters are named `input_{name}` (where `name` is the circuit's Ingest
/// name), avoiding any collision with the `w{wire_id}` namespace used for
/// intermediate variables.
pub fn emit_verifier_rust(circuit: &Circuit, fn_name: &str, expr_digest: &[u8; 32]) -> String {
    let sig_params = circuit.gadgets.iter()
        .filter_map(|g| if let Gadget::Ingest { name, .. } = g { Some(name.as_str()) } else { None })
        .map(|name| format!("input_{name}: u32"))
        .collect::<Vec<_>>()
        .join(", ");

    let mut out = String::new();
    out.push_str("// Generated by xorpl — do not edit manually.\n");
    out.push_str(&format_digest_const(expr_digest));
    out.push_str(&format!("pub fn {fn_name}({sig_params}) -> u32 {{\n"));

    for g in &circuit.gadgets {
        out.push_str(&emit_plain_gadget(g));
    }

    out.push_str("}\n");
    out
}

fn emit_plain_gadget(g: &Gadget) -> String {
    match g {
        Gadget::Ingest { name, out, .. } =>
            format!("    let w{out} = input_{name};\n"),
        Gadget::PublicConst { k, out } =>
            format!("    let w{out} = 0x{k:08x}u32;\n"),
        Gadget::SecretConst { k, out, .. } =>
            format!("    let w{out} = 0x{k:08x}u32;\n"),
        Gadget::Xor { a, b, out } =>
            format!("    let w{out} = w{a} ^ w{b};\n"),
        Gadget::XorConst { a, k, out } =>
            format!("    let w{out} = w{a} ^ 0x{k:08x}u32;\n"),
        Gadget::AndConst { a, k, out } =>
            format!("    let w{out} = w{a} & 0x{k:08x}u32;\n"),
        Gadget::Rotl { a, r, out } =>
            format!("    let w{out} = w{a}.rotate_left({r});\n"),
        Gadget::And { a, b, out, .. } =>
            format!("    let w{out} = w{a} & w{b};\n"),
        Gadget::Remask { a, out, .. } =>
            format!("    let w{out} = w{a};\n"),
        Gadget::Egress { a } =>
            format!("    w{a}\n"),
    }
}

// ---------------------------------------------------------------------------
// Register allocation
// ---------------------------------------------------------------------------

/// Compute the last step (gadget index) at which each wire is read.
/// Wires that are never read after definition have `last_use == def_step`.
fn last_use_steps(circuit: &Circuit) -> Vec<usize> {
    let n = circuit.gadgets.iter()
        .flat_map(|g| g.out().into_iter().chain(g.input_wires()))
        .max()
        .map(|m| m + 1)
        .unwrap_or(0);

    let mut last_use = vec![0usize; n];
    for (step, g) in circuit.gadgets.iter().enumerate() {
        if let Some(out) = g.out() {
            last_use[out] = step;
        }
    }
    for (step, g) in circuit.gadgets.iter().enumerate() {
        for wire in g.input_wires() {
            if step > last_use[wire] {
                last_use[wire] = step;
            }
        }
    }
    last_use
}

/// Linear-scan register allocator with a random slot-index shuffle.
///
/// Returns a `slot` vector indexed by `WireId`; only entries for wires with
/// definitions (those that appear as `g.out()`) are meaningful — others hold
/// `usize::MAX`.
///
/// The shuffle permutes slot indices with `rng` so the `r[k]` values in the
/// emitted code differ between rotations without changing circuit semantics.
fn allocate_registers(circuit: &Circuit, rng: &mut impl rand::RngCore) -> Vec<usize> {
    let last_use = last_use_steps(circuit);
    let n        = last_use.len();
    let n_steps  = circuit.gadgets.len();

    // expire_at[s] = wires whose slot becomes free at the start of step s
    //                (last_use of the wire was s-1).
    let mut expire_at: Vec<Vec<WireId>> = vec![Vec::new(); n_steps + 1];

    let mut slot   = vec![usize::MAX; n];
    let mut free   = Vec::<usize>::new(); // available indices, kept sorted ascending
    let mut n_slots = 0usize;

    for (step, g) in circuit.gadgets.iter().enumerate() {
        // Reclaim slots from wires that died before this step.
        for wire in expire_at[step].drain(..) {
            let s = slot[wire];
            let pos = free.partition_point(|&x| x < s);
            free.insert(pos, s);
        }

        // Assign a slot to this gadget's output, preferring the smallest free slot.
        if let Some(out) = g.out() {
            let s = if !free.is_empty() {
                free.remove(0)
            } else {
                let s = n_slots;
                n_slots += 1;
                s
            };
            slot[out] = s;
            // The slot becomes reclaimable once this wire's last read has passed.
            expire_at[last_use[out] + 1].push(out);
        }
    }

    if n_slots == 0 {
        return slot;
    }

    // Shuffle the slot indices for structural variation across rotations.
    let mut perm: Vec<usize> = (0..n_slots).collect();
    use rand::seq::SliceRandom;
    perm.shuffle(rng);

    for s in slot.iter_mut() {
        if *s != usize::MAX {
            *s = perm[*s];
        }
    }

    slot
}

// ---------------------------------------------------------------------------
// Constant pool and gadget emission
// ---------------------------------------------------------------------------

/// Flatten every `BakedGadget::consts` into one pool `Vec` and return a
/// parallel `Vec` of starting indices so gadget `i`'s constants are
/// `pool[starts[i]..starts[i+1]]`.
fn build_pool(masked: &MaskedCircuit) -> (Vec<u32>, Vec<usize>) {
    let mut pool = Vec::new();
    let mut starts = Vec::new();
    for mg in masked.baked_consts() {
        starts.push(pool.len());
        pool.extend_from_slice(mg);
    }
    starts.push(pool.len()); // sentinel
    (pool, starts)
}

/// Emit the Rust statement(s) for one gadget.
///
/// `p` is the gadget's starting index in the flattened constant pool.
/// `slot` maps each WireId to its register array index.
/// AND emits a Beaver expansion block; all other gadgets emit a single
/// assignment.  Egress emits the tail expression (no semicolon).
fn emit_gadget(g: &Gadget, p: usize, slot: &[usize]) -> String {
    match g {
        Gadget::PublicConst { out, .. } => {
            let so = slot[*out];
            format!("    r[{so}] = POOL[{p}];\n")
        }
        Gadget::SecretConst { out, .. } => {
            let so = slot[*out];
            format!("    r[{so}] = POOL[{p}];\n")
        }
        Gadget::Ingest { name, out, .. } => {
            let so = slot[*out];
            format!("    r[{so}] = {name} ^ POOL[{p}];\n")
        }
        Gadget::Xor { a, b, out } => {
            let (sa, sb, so) = (slot[*a], slot[*b], slot[*out]);
            format!("    r[{so}] = r[{sa}] ^ r[{sb}];\n")
        }
        Gadget::XorConst { a, out, .. } => {
            let (sa, so) = (slot[*a], slot[*out]);
            format!("    r[{so}] = r[{sa}] ^ POOL[{p}];\n")
        }
        Gadget::AndConst { a, out, .. } => {
            let (sa, so) = (slot[*a], slot[*out]);
            format!("    r[{so}] = r[{sa}] & POOL[{p}];\n")
        }
        Gadget::Rotl { a, r, out } => {
            let (sa, so) = (slot[*a], slot[*out]);
            format!("    r[{so}] = r[{sa}].rotate_left({r});\n")
        }
        Gadget::And { a, b, out, .. } => {
            let (sa, sb, so) = (slot[*a], slot[*b], slot[*out]);
            let (p1, p2) = (p + 1, p + 2);
            let mut s = String::new();
            s.push_str(&format!("    r[{so}] = {{\n"));
            s.push_str(&format!("        let (t, ma, mb) = (POOL[{p}], POOL[{p1}], POOL[{p2}]);\n"));
            s.push_str(         "        let mut z = t;\n");
            s.push_str(&format!("        z ^= r[{sa}] & mb;\n"));
            s.push_str(&format!("        z ^= r[{sb}] & ma;\n"));
            s.push_str(&format!("        z ^= r[{sa}] & r[{sb}];\n"));
            s.push_str(         "        z\n");
            s.push_str(         "    };\n");
            s
        }
        Gadget::Remask { a, out, .. } => {
            let (sa, so) = (slot[*a], slot[*out]);
            format!("    r[{so}] = r[{sa}] ^ POOL[{p}];\n")
        }
        Gadget::Egress { a } => {
            let sa = slot[*a];
            format!("    r[{sa}] ^ POOL[{p}]\n")
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::expr::Expr;
    use crate::lower::lower_to_circuit;

    fn or_rotl_circuit() -> Circuit {
        let a = Expr::input("a");
        let b = Expr::input("b");
        let c = Expr::secret_const(0x9e37_79b9);
        let expr = Expr::rotl(Expr::xor(Expr::or(a, b), c), 5);
        lower_to_circuit(&expr)
    }

    #[test]
    fn verifier_has_correct_signature() {
        let circuit  = or_rotl_circuit();
        let emitted  = emit_verifier_rust(&circuit, "my_fn", &[0u8; 32]);
        assert!(emitted.contains("pub fn my_fn(input_a: u32, input_b: u32) -> u32 {"),
            "wrong signature:\n{emitted}");
        assert!(emitted.contains("pub const EXPR_DIGEST"),
            "missing EXPR_DIGEST:\n{emitted}");
    }

    #[test]
    fn verifier_agrees_with_circuit_eval() {
        let circuit = or_rotl_circuit();
        let emitted = emit_verifier_rust(&circuit, "checksum", &[0u8; 32]);

        // Spot-check a few expected lines against what circuit.eval() does.
        // The verifier emits w{id} = <op>; we verify these match the gadget list.
        let inputs: std::collections::HashMap<String, u32> =
            [("a", 0x1234_5678u32), ("b", 0xDEAD_BEEFu32)]
            .iter().map(|&(k, v)| (k.to_string(), v)).collect();
        let vals = circuit.eval(&inputs);
        let expected = vals[&circuit.egress];

        // Cross-check: formula matches known output.
        let known = ((0x1234_5678u32 | 0xDEAD_BEEFu32) ^ 0x9e37_79b9u32).rotate_left(5);
        assert_eq!(expected, known);

        // Structural: ingest wires reference their prefixed parameter names.
        assert!(emitted.contains("let w0 = input_a;"), "missing ingest a:\n{emitted}");
        assert!(emitted.contains("let w1 = input_b;"), "missing ingest b:\n{emitted}");
        assert!(emitted.contains("rotate_left(5)"),  "missing rotl:\n{emitted}");
        assert!(emitted.contains("0x9e3779b9u32"), "missing secret const:\n{emitted}");
    }

    #[test]
    fn verifier_remask_is_transparent() {
        use crate::circuit::Builder;
        let mut builder = Builder::new();
        let wa = builder.ingest("x");
        let wr = builder.remask(wa);
        let circuit = builder.build(wr);
        let emitted = emit_verifier_rust(&circuit, "f", &[0u8; 32]);
        // Remask emits an identity assignment; no POOL reference.
        assert!(emitted.contains("let w1 = w0;"), "remask should be identity:\n{emitted}");
        assert!(!emitted.contains("POOL"), "verifier must not reference POOL:\n{emitted}");
    }

    #[test]
    fn verifier_contains_no_pool_or_beaver() {
        let circuit = or_rotl_circuit();
        let emitted = emit_verifier_rust(&circuit, "f", &[0u8; 32]);
        assert!(!emitted.contains("POOL"),  "verifier must not reference POOL");
        assert!(!emitted.contains("let (t, ma, mb)"), "verifier must not use Beaver triples");
    }
}
