//! Emission: `ConcreteVm` → Rust source code.
//!
//! This module takes a baked, concrete VM and emits a standalone Rust function
//! that implements the same computation without any VM machinery — just array
//! accesses, XOR, AND, and rotation on `u32` values.
//!
//! The emitted function is what gets shipped to the client (compiled to Wasm
//! or included in a JS bundle). A new rotation means re-running
//! `ConcreteVm::from_circuit` with a new seed and re-emitting; the circuit
//! structure stays the same, only the constants change.
//!
//! # Emitted shape
//!
//! ```rust,ignore
//! pub fn checksum(a: u32, b: u32) -> u32 {
//!     const POOL: &[u32] = &[0xdeadbeef, 0xcafebabe, /* ... */];
//!     let mut r = [0u32; N];           // N = number of non-egress wires
//!
//!     // One block per gadget, in topological order:
//!
//!     r[0] = a ^ POOL[0];              // INGEST "a"
//!     r[1] = b ^ POOL[1];              // INGEST "b"
//!     r[2] = POOL[2];                  // SECRET_CONST  (k^mask baked in)
//!     r[3] = r[0] ^ r[1];             // XOR  (free)
//!     r[4] = {                         // AND  (Beaver triple expansion)
//!         let (t, ma, mb) = (POOL[3], POOL[4], POOL[5]);
//!         let mut z = t;
//!         z ^= r[0] & mb;
//!         z ^= r[1] & ma;
//!         z ^= r[0] & r[1];
//!         z
//!     };
//!     // ...
//!     r[K] ^ POOL[M]                   // EGRESS: XOR with unmask delta
//! }
//! ```
//!
//! # Register allocation
//!
//! The initial implementation uses a direct 1:1 mapping: WireId N → `r[N]`.
//! This is correct and simple — array size equals the number of non-egress
//! wires. A future live-range allocator could reduce the array to
//! O(max-live-wires) slots, shrinking the emitted function's stack frame for
//! large circuits (e.g. a full ChaCha double-round with 500+ gadgets).
//!
//! # Constant pool layout
//!
//! Constants are emitted in gadget order, concatenated into a single `POOL`
//! slice. Each gadget records how many pool entries it owns (already tracked
//! in `BakedGadget::consts`), so indexing is straightforward.
//!
//! # Future: structured output
//!
//! The current design returns a `String`. If the emission target changes (e.g.
//! emitting JavaScript or Wasm bytecode directly), this function's signature
//! should change to return a `proc_macro2::TokenStream` or a target-specific
//! IR, keeping the gadget-walking logic intact.

use crate::vm::{ConcreteVm, Gadget};

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/// Emit a self-contained Rust source file containing a single function for
/// the given concrete VM.
///
/// `fn_name` — the name of the emitted function (also the file stem).
///
/// The function's parameter list is derived directly from the circuit's
/// `Gadget::Ingest` entries in topological order — each ingest's `name`
/// field becomes a `u32` parameter.  The caller must ensure those names are
/// valid Rust identifiers.
///
/// Returns a `String` containing a complete Rust source file that can be
/// written to disk and compiled independently of this crate.
pub fn emit_rust(vm: &ConcreteVm, fn_name: &str) -> String {
    let (pool, pool_starts) = build_pool(vm);
    let n_regs = vm.circuit.gadgets.iter()
        .filter_map(|g| g.out())
        .max()
        .map(|m| m + 1)
        .unwrap_or(0);

    // Derive parameter list from ingest gadgets in topological order.
    let sig_params = vm.circuit.gadgets.iter()
        .filter_map(|g| if let Gadget::Ingest { name, .. } = g { Some(name.as_str()) } else { None })
        .map(|name| format!("{name}: u32"))
        .collect::<Vec<_>>()
        .join(", ");

    let mut out = String::new();

    // File header
    out.push_str("// Generated by `cargo run --bin regen_fixtures` — do not edit manually.\n");

    // Function signature
    out.push_str(&format!("pub fn {fn_name}({sig_params}) -> u32 {{\n"));

    // Constant pool
    out.push_str("    const POOL: &[u32] = &[\n");
    for &v in &pool {
        out.push_str(&format!("        0x{v:08x},\n"));
    }
    out.push_str("    ];\n");

    // Register array
    out.push_str(&format!("    let mut r = [0u32; {n_regs}];\n"));

    // One statement per gadget, in topological order
    for (idx, g) in vm.circuit.gadgets.iter().enumerate() {
        out.push_str(&emit_gadget(g, pool_starts[idx]));
    }

    out.push_str("}\n");
    out
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/// Flatten every `BakedGadget::consts` into one pool `Vec` and return a
/// parallel `Vec` of starting indices so gadget `i`'s constants are
/// `pool[starts[i]..starts[i+1]]`.
fn build_pool(vm: &ConcreteVm) -> (Vec<u32>, Vec<usize>) {
    let mut pool = Vec::new();
    let mut starts = Vec::new();
    for bg in &vm.baked {
        starts.push(pool.len());
        pool.extend_from_slice(&bg.consts);
    }
    starts.push(pool.len()); // sentinel
    (pool, starts)
}

/// Emit the Rust statement(s) for one gadget.
///
/// `p` is the gadget's starting index in the flattened constant pool.
/// AND emits a four-line Beaver expansion block; all other gadgets emit a
/// single assignment.  Egress emits the tail expression (no semicolon).
fn emit_gadget(g: &Gadget, p: usize) -> String {
    match g {
        Gadget::PublicConst { out, .. } =>
            format!("    r[{out}] = POOL[{p}];\n"),

        Gadget::SecretConst { out, .. } =>
            format!("    r[{out}] = POOL[{p}];\n"),

        Gadget::Ingest { name, out, .. } =>
            format!("    r[{out}] = {name} ^ POOL[{p}];\n"),

        Gadget::Xor { a, b, out } =>
            format!("    r[{out}] = r[{a}] ^ r[{b}];\n"),

        Gadget::XorConst { a, out, .. } =>
            format!("    r[{out}] = r[{a}] ^ POOL[{p}];\n"),

        Gadget::AndConst { a, out, .. } =>
            format!("    r[{out}] = r[{a}] & POOL[{p}];\n"),

        Gadget::Rotl { a, r, out } =>
            format!("    r[{out}] = r[{a}].rotate_left({r});\n"),

        Gadget::And { a, b, out, .. } => {
            let (p1, p2) = (p + 1, p + 2);
            let mut s = String::new();
            s.push_str(&format!("    r[{out}] = {{\n"));
            s.push_str(&format!("        let (t, ma, mb) = (POOL[{p}], POOL[{p1}], POOL[{p2}]);\n"));
            s.push_str(         "        let mut z = t;\n");
            s.push_str(&format!("        z ^= r[{a}] & mb;\n"));
            s.push_str(&format!("        z ^= r[{b}] & ma;\n"));
            s.push_str(&format!("        z ^= r[{a}] & r[{b}];\n"));
            s.push_str(         "        z\n");
            s.push_str(         "    };\n");
            s
        }

        Gadget::Remask { a, out, .. } =>
            format!("    r[{out}] = r[{a}] ^ POOL[{p}];\n"),

        Gadget::Egress { a } =>
            format!("    r[{a}] ^ POOL[{p}]\n"),
    }
}
